import tigersNest from "@/assets/tigers-nest.jpg";
import culture from "@/assets/culture.jpg";
import trekking from "@/assets/trekking.jpg";
import punakha from "@/assets/punakha.jpg";
import thimphu from "@/assets/thimphu.jpg";
import bumthang from "@/assets/bumthang.jpg";
import festival from "@/assets/festival.jpg";
import birdwatching from "@/assets/birdwatching.jpg";
import corporate from "@/assets/corporate.jpg";
import yoga from "@/assets/yoga.jpg";
import wedding from "@/assets/wedding.jpg";
import type { Tour } from "@/components/TourCard";

const commonExcludes = [
  "International / regional airfare",
  "Sustainable Development Fee (SDF) — collected directly by TCB",
  "Personal expenses, tips and travel insurance",
  "Any activity or meal not specified in the itinerary",
];

export const tours: Tour[] = [
  {
    slug: "group-tours-classic-bhutan-circuit",
    title: "Group Tours — Classic Bhutan Circuit",
    category: "Group Tours",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Classic Bhutan Circuit",
    location: "Paro · Thimphu · Punakha",
    price: 1290,
    image: punakha,
    desc: "A fixed-departure circuit for groups of 15–40 pax combining bulk hotel allocations, coach logistics and Bhutan's most iconic sights.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "15–40 pax",
    idealFor: "B2B group blocks, school/corporate delegations and fixed-departure travellers",
    overview:
      "Designed for fixed-departure groups of 15–40 pax, this circuit combines bulk hotel allocations and high-capacity coach logistics with Bhutan's most iconic sights. It is the flagship itinerary for B2B agents and school/corporate blocks travelling together.",
    highlights: [
      "Covers all four flagship destinations — Thimphu, Punakha and Paro — in a proven circuit",
      "Optimised for bulk hotel allocation and high-capacity coach logistics",
      "Includes the iconic Taktsang (Tiger's Nest) hike, Bhutan's most photographed excursion",
      "Dedicated Golden Takin Holidays tour leader throughout the journey",
      "Farewell cultural evening with traditional mask-dance performance",
    ],
    includes: [
      "5 nights' accommodation on twin-sharing basis (3★ to 4★ category)",
      "Daily breakfast, lunch & dinner (Bhutanese/Continental/Indian options)",
      "All ground transport in private coach with English/Hindi-speaking licensed guide",
      "Entrance fees to all monuments & museums listed in itinerary",
      "SDF processing assistance",
      "Bhutan visa/permit processing",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Paro International Airport arrival. Private coach transfer to Thimphu (1 hr). Evening visit to Tashichho Dzong and a stroll through Thimphu town. Overnight in Thimphu." },
      { day: 2, title: "Thimphu sightseeing", desc: "Full day covering Buddha Dordenma Statue, Motithang Takin Preserve, National Memorial Chorten and the Institute of Zorig Chusum. Group photo session at the dzong courtyard. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha via Dochula Pass", desc: "Scenic drive to Punakha via Dochula Pass (3,100m) with panoramic Himalayan views among the 108 memorial chortens. Afternoon visit to Punakha Dzong at the confluence of Pho Chhu and Mo Chhu. Overnight in Punakha." },
      { day: 4, title: "Punakha — Paro", desc: "Morning walk to Chimi Lhakhang through rice terraces, followed by the scenic drive back to Paro. Evening at leisure to explore Paro town's traditional shopfronts and handicraft stalls. Overnight in Paro." },
      { day: 5, title: "Hike to Taktsang (Tiger's Nest) Monastery", desc: "Signature group excursion — guided hike (round trip approx. 5 hrs) to Taktsang Monastery perched at 3,120m. Group lunch at the cafeteria with valley views. Farewell dinner with cultural mask-dance performance. Overnight in Paro." },
      { day: 6, title: "Departure", desc: "Transfer to Paro International Airport for onward journey. Golden Takin Holidays representatives assist with group check-in." },
    ],
  },
  {
    slug: "family-tours",
    title: "Family Tours",
    category: "Family Tours",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Multi-Generational Bhutan Discovery",
    location: "Paro · Thimphu · Punakha",
    price: 1690,
    image: culture,
    desc: "A gentle-paced itinerary blending kid-friendly activities, elder-comfortable logistics, private vehicles and an immersive farmhouse homestay.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "Oct–Dec · Mar–Apr",
    groupSize: "Private tour — any family size",
    idealFor: "Multi-generational families with children and/or elderly travellers",
    overview:
      "A gentle-paced itinerary curated for multi-generational travel, blending kid-friendly activities, elder-comfortable logistics, private chauffeured vehicles and immersive homestay experiences for a wholesome family adventure in Bhutan.",
    highlights: [
      "Slower daily pace with shorter drive segments",
      "Hands-on kid-friendly activities: archery, art workshops, pony rides",
      "Authentic farmhouse homestay for cultural immersion",
      "Private chauffeur-driven vehicle throughout — no group coach",
      "Optional pony-assisted ascent for the Taktsang hike",
    ],
    includes: [
      "6 nights' accommodation (family rooms / interconnecting rooms available)",
      "Daily breakfast, lunch and dinner including farmhouse-hosted meal",
      "Private vehicle with child seats (on request)",
      "All entrance fees and homestay experience fee",
      "SDF and visa processing assistance",
      "Complimentary welcome gift and farewell keepsake for children",
    ],
    excludes: [...commonExcludes, "Pony rental fee for Taktsang hike (payable locally, optional)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Warm welcome at Paro Airport and an easy private drive to Thimphu. Evening hotel check-in and a relaxed family dinner featuring mild Bhutanese dishes suitable for children." },
      { day: 2, title: "Thimphu with the kids", desc: "A family-friendly day at Motithang Takin Preserve to meet Bhutan's national animal, followed by an archery demonstration and a hands-on painting session at the Voluntary Artists' Studio." },
      { day: 3, title: "Thimphu — Punakha", desc: "Drive to Punakha via Dochula Pass. Visit Punakha Dzong and enjoy a riverside walk, followed by a crossing of the longest suspension bridge in Bhutan." },
      { day: 4, title: "Punakha homestay experience", desc: "A full day at a local farmhouse — cook traditional meals, learn local customs, enjoy ara and butter tea, and join a friendly archery match with village hosts." },
      { day: 5, title: "Punakha — Paro", desc: "Scenic drive back to Paro. Afternoon at leisure — pony rides for younger children and a relaxed walk through Paro town's craft shops." },
      { day: 6, title: "Family hike to Taktsang", desc: "An easier-paced hike with pony option available to the cafeteria viewpoint. Farewell dinner with a private family cultural show." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport for departure, with keepsake gifts presented to the family by Golden Takin Holidays." },
    ],
  },
  {
    slug: "nature-and-eco-tours",
    title: "Nature & Eco Tours",
    category: "Nature & Eco",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Flora, Fauna & Conservation Trails",
    location: "Thimphu · Punakha · Phobjikha",
    price: 1490,
    image: bumthang,
    desc: "Conservation-led travel through Bhutan's forests, wetlands and glacial valleys with naturalist guides.",
    rating: 4.8,
    difficulty: "Moderate",
    bestTime: "Oct–Mar (crane season) · Apr–May (blooms)",
    groupSize: "2–12 pax, naturalist-guided",
    idealFor: "Nature lovers, eco-conscious travellers and small groups interested in Bhutan's conservation model",
    overview:
      "A conservation-focused circuit exploring Bhutan's forests, wetlands and protected valleys — from the Phobjikha black-necked crane habitat to rhododendron and magnolia trails — guided by trained naturalists.",
    highlights: [
      "Black-necked crane habitat visit in the Phobjikha wetlands",
      "Alpine meadow and rhododendron trails around Dochula Pass",
      "Community-based conservation and eco-lodge stays",
      "Naturalist-guided walks with species checklists",
      "Low-impact travel following Bhutan's carbon-negative model",
    ],
    includes: [
      "5 nights' accommodation in eco-lodges and guesthouses",
      "Daily breakfast, lunch and dinner",
      "Naturalist guide and private vehicle with driver",
      "All park entrance and conservation area fees",
      "SDF and visa processing assistance",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro Airport and private drive to Thimphu. Evening conservation briefing with your naturalist guide." },
      { day: 2, title: "Thimphu conservation circuit", desc: "Motithang Takin Preserve, the Royal Botanical Park and a forest walk covering Bhutan's endemic flora and protected species." },
      { day: 3, title: "Thimphu — Punakha via Dochula", desc: "Drive to Punakha over Dochula Pass with its 108 chortens and alpine meadow trail. Riverside birding in the Punakha valley." },
      { day: 4, title: "Phobjikha Valley — wetland conservation", desc: "Transfer to the glacial Phobjikha Valley. Visit the Black-Necked Crane Information Centre and walk the Gangtey Nature Trail among grazing yaks." },
      { day: 5, title: "Phobjikha — Paro", desc: "Morning wetland walk, then a scenic drive to Paro with panoramic Himalayan ridgeline stops along the way." },
      { day: 6, title: "Paro valley walk — departure", desc: "Kyichu Lhakhang and a final riverside valley walk before transfer to Paro International Airport." },
    ],
  },
  {
    slug: "geographical-expedition",
    title: "Geographical Expedition",
    category: "Geographical Expedition",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Himalayan Thrust & Landform Studies",
    location: "Paro · Punakha · Haa · Chele La",
    price: 1590,
    image: trekking,
    desc: "A fieldwork-oriented expedition through thrust zones, river confluences and glacial landforms, accompanied by a local geologist-guide.",
    rating: 4.7,
    difficulty: "Moderate",
    bestTime: "Apr–Jun · Sep–Nov",
    groupSize: "6–20 pax with geologist-guide",
    idealFor: "University geology/geography departments, research groups and expedition-style enthusiasts",
    overview:
      "An academic field itinerary built around the Himalayan thrust belt: exposed rock strata, river confluences, glacial valleys and high-pass landform observation, with stable weather windows for fieldwork and pass crossings.",
    highlights: [
      "Accompanied by a local geologist-guide throughout",
      "Exposed rock strata and thrust-zone field stops",
      "Punakha river confluence and fluvial landform study",
      "Chele La (3,988m) high-pass observation point",
      "Field notes, sampling stops and evening debrief sessions",
    ],
    includes: [
      "6 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Private expedition vehicle, driver and geologist-guide",
      "All field-site permits and entrance fees",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Specialist survey equipment and sample export permits"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Arrival briefing on Himalayan tectonics and the week's field plan. Overnight in Thimphu." },
      { day: 2, title: "Exposed rock strata", desc: "Field stops along road cuttings displaying folded and faulted strata of the Lesser Himalayan sequence." },
      { day: 3, title: "Dochula panoramic view", desc: "High-pass panorama of the eastern Himalayan range with orientation to glaciated peaks and watershed lines." },
      { day: 4, title: "Punakha river confluence", desc: "Study of the Pho Chhu and Mo Chhu confluence — terraces, braided channels and flood-plain deposition." },
      { day: 5, title: "Haa valley landscape", desc: "Transfer to the Haa valley for glacial trough and valley-floor morphology observation." },
      { day: 6, title: "Chele La pass", desc: "Ascent to Chele La for alpine landform, tree-line and weathering profile studies with valley-scale photography." },
      { day: 7, title: "Departure", desc: "Paro valley sunrise viewpoint, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "birdwatching-tours",
    title: "Birdwatching Tours",
    category: "Birdwatching",
    duration: "8 Days",
    nights: "8 Days / 7 Nights",
    tagline: "Ornithology Expedition",
    location: "Paro · Thimphu · Punakha · Phobjikha",
    price: 1890,
    image: birdwatching,
    desc: "An expertly guided itinerary targeting Bhutan's avian diversity, from the elusive Ward's Trogon to the endangered Black-Necked Crane.",
    rating: 4.9,
    difficulty: "Moderate",
    bestTime: "Mar–May · Oct–Nov (peak migration)",
    groupSize: "Small groups with expert ornithologist guide",
    idealFor: "Ornithologists and avid birders",
    overview:
      "A highly focused, expertly guided itinerary designed for ornithology enthusiasts, targeting Bhutan's diverse avian species — from the elusive Ward's Trogon to the endangered Black-Necked Crane — with stops at key birding hotspots.",
    highlights: [
      "Expert ornithologist guide throughout",
      "High-altitude birding across Lawa La and Dochula",
      "Riverine species sightings in the Punakha valley",
      "Black-Necked Crane habitat visit in Phobjikha",
      "Species checklist provided and daily briefings",
    ],
    includes: [
      "All accommodation on twin-sharing basis including a retreat lodge stay in Punakha",
      "All meals (vegetarian options available throughout)",
      "Licensed ornithologist guide and private vehicle with driver",
      "All entrance fees and airport transfers",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Optics rental"],
    itinerary: [
      { day: 1, title: "Arrival — transfer to Thimphu", desc: "Evening birding checklist briefing. Overnight in hotel, Thimphu." },
      { day: 2, title: "Thimphu to Punakha via Lawa La", desc: "Target high-altitude species such as Satyr Tragopan along the pass. Overnight in hotel, Punakha." },
      { day: 3, title: "Punakha — Jigme Dorji National Park", desc: "Riverside birding for Ibisbill and riverine specialists. Overnight in hotel, Punakha." },
      { day: 4, title: "Punakha to Phobjikha", desc: "Drive through temperate forest for Ward's Trogon, then descend to the valley wetlands. Overnight in guesthouse, Phobjikha." },
      { day: 5, title: "Phobjikha full-day birding", desc: "Black-Necked Crane habitat and wetland circuit with the Gangtey ridge forest edge." },
      { day: 6, title: "Phobjikha to Paro", desc: "Return journey with final birding stops en route. Overnight in hotel, Paro." },
      { day: 7, title: "Paro valley & Taktsang trail birding", desc: "Early morning birding on the Tiger's Nest trail and along the Paro Chhu." },
      { day: 8, title: "Departure", desc: "Final checklist review and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "corporate-meetups-mice",
    title: "Corporate Meetups & MICE",
    category: "Corporate & MICE",
    duration: "4 Days",
    nights: "3 Nights / 4 Days",
    tagline: "MICE & Executive Retreats",
    location: "Thimphu — Paro",
    price: 1390,
    image: corporate,
    desc: "Full-scale corporate off-site programs with tech-enabled venues, custom gala dinners and structured team-building.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Year-round",
    groupSize: "20–200 delegates",
    idealFor: "Corporate off-sites, conferences, leadership retreats and incentive groups",
    overview:
      "Full-scale corporate off-site programs — tech-enabled conference venues housed within dzong-inspired buildings, customised gala dinners featuring traditional music and dance, and structured team-building activities across Thimphu and Paro.",
    highlights: [
      "Tech-enabled conference venues with AV and stage management",
      "Leadership retreat and breakout facilitation",
      "Custom gala dinners with traditional performance",
      "Structured team-building in Paro valley",
      "Dedicated event coordinator and delegate logistics desk",
    ],
    includes: [
      "3 nights' accommodation on twin-sharing or single-occupancy basis",
      "All meals including one customised gala dinner",
      "Conference venue hire with AV setup",
      "Licensed guide, private coaches and all airport transfers",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Additional venue branding and production beyond standard setup"],
    itinerary: [
      { day: 1, title: "Arrival & welcome reception", desc: "Airport welcome with traditional greeting, hotel check-in and evening welcome reception in Thimphu." },
      { day: 2, title: "Conference day in Thimphu", desc: "Full-day session in a fully-equipped, tech-enabled conference hall with breakout rooms and catered breaks." },
      { day: 3, title: "Team-building in Paro & gala dinner", desc: "Transfer to Paro for outdoor team-building including traditional archery, followed by a custom gala dinner with mask dances." },
      { day: 4, title: "Optional site visit — departure", desc: "Optional executive site visit or short cultural excursion before transfer to Paro International Airport." },
    ],
  },
  {
    slug: "yoga-and-meditation-tours",
    title: "Yoga & Meditation Tours",
    category: "Yoga & Wellness",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Wellness Retreats in the Last Shangri-La",
    location: "Paro · Thimphu · Punakha",
    price: 1790,
    image: yoga,
    desc: "Spiritual retreats hosted amid isolated monasteries and wellness resorts, with daily practice led by local masters.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "Spring and autumn preferred (year-round)",
    groupSize: "Yoga practitioners and meditation retreat groups",
    idealFor: "Wellness seekers, yoga practitioners and retreat groups",
    overview:
      "Spiritual retreats hosted amid isolated monasteries and specialised wellness resorts, integrating local masters, daily meditation practice and personalised holistic treatments at a retreat-styled pace.",
    highlights: [
      "Daily guided yoga and meditation sessions",
      "Traditional hot-stone bath (Dotsho)",
      "Riverside and monastery-courtyard meditation",
      "Silent meditation at Dochula Pass's 108 chortens",
      "Mindful, slow-paced hike to Taktsang Monastery",
    ],
    includes: [
      "6 nights' wellness accommodation",
      "Daily breakfast, lunch and dinner (wellness menu)",
      "Daily yoga/meditation sessions and meditation cushion/mat",
      "One Dotsho hot-stone bath",
      "Licensed guide and private vehicle throughout",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Additional spa treatments beyond the included session"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Arrival and transfer with welcome retreat briefing. Evening grounding meditation session." },
      { day: 2, title: "Thimphu wellness day", desc: "Morning yoga session, guided meditation walk to Tango Monastery and an afternoon Dotsho hot-stone bath." },
      { day: 3, title: "Thimphu — Punakha retreat", desc: "Drive to Punakha via Dochula Pass with silent meditation at the 108 chortens. Evening riverside meditation." },
      { day: 4, title: "Punakha immersion day", desc: "Immersion at a monastery retreat centre: pranayama, dharma talk and afternoon nature-walk meditation." },
      { day: 5, title: "Punakha — Paro", desc: "Drive to Paro. Evening restorative yoga as the sun sets, followed by a wellness dinner." },
      { day: 6, title: "Meditative hike to Taktsang", desc: "Slow, mindful hike to Taktsang (Tiger's Nest) with contemplation stops. Closing group meditation." },
      { day: 7, title: "Departure", desc: "Optional sunrise meditation before transfer to Paro International Airport." },
    ],
  },
  {
    slug: "school-college-cultural-exchange",
    title: "School & College Cultural Exchange",
    category: "School & College",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "GNH, Heritage & Sustainable Architecture Circuit",
    location: "Thimphu · Punakha · Paro",
    price: 1150,
    image: festival,
    desc: "An educational circuit built around Gross National Happiness, heritage conservation and traditional building crafts.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "October–March",
    groupSize: "20–60 students",
    idealFor: "Schools, colleges and university study groups",
    overview:
      "A structured student exchange circuit exploring Gross National Happiness philosophy, heritage governance, traditional rammed-earth architecture and hands-on craft workshops with Bhutanese master artisans.",
    highlights: [
      "Orientation session on GNH philosophy with an expert guide",
      "Guided study of Tashichho Dzong and Bhutanese governance",
      "Hands-on rammed-earth and wooden formwork workshop",
      "Heritage talk inside the Punakha Dzong assembly chamber",
      "Traditional weaving participation in a Paro village",
    ],
    includes: [
      "6 nights' student accommodation on sharing basis",
      "Daily breakfast, lunch and dinner",
      "All workshop, entrance and heritage-site fees",
      "Private coaches, licensed guide and teacher escorts support",
      "SDF and visa processing assistance",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival & GNH orientation", desc: "Orientation session in a Thimphu conference hall where an expert guide introduces the GNH philosophy to the student group." },
      { day: 2, title: "Tashichho Dzong study visit", desc: "Guided tour of the courtyards of Tashichho Dzong with an explanation of Bhutan's official governance structure." },
      { day: 3, title: "Sustainable architecture workshop", desc: "Hands-on workshop where a Bhutanese master artisan demonstrates rammed-earth mixing and wooden formwork construction." },
      { day: 4, title: "Punakha Dzong heritage talk", desc: "History session inside the assembly chamber of Punakha Dzong covering conservation and restoration practice." },
      { day: 5, title: "Traditional weaving in Paro", desc: "Active participation in a traditional weaving session in a Paro village, guided by local weavers." },
      { day: 6, title: "Taktsang group hike", desc: "Guided student hike to Taktsang Monastery with a reflection session and group presentations in the evening." },
      { day: 7, title: "Departure", desc: "Farewell group photo and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "honeymoon-trips",
    title: "Honeymoon Trips",
    category: "Honeymoon",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Private Valley Romance",
    location: "Paro · Thimphu · Punakha",
    price: 2190,
    image: tigersNest,
    desc: "A private, exclusively-for-two journey of candlelit dinners, blessing ceremonies and sunrise hikes across Bhutan's valleys.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Private — exclusively for the couple",
    idealFor: "Honeymooners and couples seeking a private valley romance",
    overview:
      "A slow, private itinerary designed exclusively for couples — chauffeured valley drives, a traditional blessing ceremony, candlelit dinners and a sunrise hike to Taktsang, with intimate accommodation throughout.",
    highlights: [
      "Fully private chauffeur-driven vehicle — no group travel",
      "Traditional Punakha blessing ceremony for the couple",
      "Candlelit private dinners and couples spa session",
      "Sunrise hike to Taktsang Monastery",
      "Romantic photography stops across three valleys",
    ],
    includes: [
      "6 nights' boutique accommodation in couple/deluxe rooms",
      "Daily breakfast, lunch and dinner including private candlelit dinners",
      "Private vehicle with chauffeur throughout",
      "Blessing ceremony arrangement and all entrance fees",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Professional photography package (available on request)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Private welcome at Paro Airport, scenic drive to Thimphu and a relaxed evening at your boutique hotel." },
      { day: 2, title: "Thimphu romance day", desc: "A private tour of Thimphu including Buddha Dordenma, an archery demonstration and a hands-on painting session at the Voluntary Artists' Studio." },
      { day: 3, title: "Thimphu — Punakha", desc: "Drive to Punakha via Dochula Pass. Visit Punakha Dzong and enjoy a riverside walk and the suspension bridge crossing." },
      { day: 4, title: "Punakha blessing ceremony", desc: "A traditional Buddhist blessing ceremony for the couple, followed by butter tea with the hosts and a private riverside lunch." },
      { day: 5, title: "Punakha — Paro", desc: "Scenic drive back to Paro. Afternoon at leisure with a couples spa session and a relaxed walk through Paro town's craft shops." },
      { day: 6, title: "Sunrise hike to Taktsang", desc: "An easy-paced sunrise hike to the Tiger's Nest viewpoint, followed by a private farewell dinner with a cultural performance." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport with a farewell keepsake from Golden Takin Holidays." },
    ],
  },
  {
    slug: "himalayan-wedding-ceremonies",
    title: "Himalayan Wedding Ceremonies",
    category: "Weddings",
    duration: "Custom",
    nights: "Custom Days / Nights",
    tagline: "Destination Weddings in the Land of Happiness",
    location: "Paro · Thimphu · Punakha · Gangtey",
    price: 2890,
    image: wedding,
    desc: "Fully bespoke destination weddings with exclusive private venues, cultural performances and complete guest logistics.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "All year (clear winter skies)",
    groupSize: "Fully bespoke — couples and guest parties",
    idealFor: "Couples, intimate families and destination wedding seekers",
    overview:
      "A celebration-focused, leisure-paced program hosted at exclusive private venues and riverside wellness lodges, with traditional ceremonies, curated feasts and full guest logistics management across four valleys.",
    highlights: [
      "Dedicated wedding coordination team",
      "Exclusive private venues across Paro, Thimphu, Punakha and Gangtey",
      "Traditional cultural performances and blessings",
      "Scenic photography locations and curated celebration dinners",
      "Complete guest logistics management",
    ],
    includes: [
      "All luxury accommodation for the couple and guest party",
      "All special event venues and dedicated event coordinator",
      "Cultural performances and curated celebration menus",
      "Professional photography package",
      "Private vehicles and visa assistance",
    ],
    excludes: [...commonExcludes, "Personal décor choices beyond the standard package", "Additional activities"],
    itinerary: [
      { day: 1, title: "Private welcome — Paro to Thimphu", desc: "Private transfer, custom welcome and celebration briefing. Overnight at Paro or Thimphu." },
      { day: 2, title: "Culture & connection — Thimphu", desc: "Visit Buddha Dordenma and traditional arts centres, followed by a pre-wedding lunch. Overnight at retreat, Thimphu." },
      { day: 3, title: "Mountain vows — Thimphu", desc: "Bespoke ceremony at a private venue with traditional Bhutanese elements. Overnight at retreat, Thimphu." },
      { day: 4, title: "Valley romance — Punakha", desc: "Drive over Dochula Pass, check in to the resort and enjoy a couples spa session, photos at Punakha Dzong and a private riverside lunch." },
      { day: 5, title: "Celebration & culture — Gangtey", desc: "Drive to Gangtey for a private celebration dinner with mask dances. Overnight at retreat, Gangtey." },
      { day: 6, title: "Hike & heritage — Gangtey", desc: "Optional brief nature hike and a local monastery visit for a closing blessing." },
      { day: 7, title: "Departure — Paro to airport", desc: "Private transfer to Paro International Airport." },
    ],
  },
];

export const categories = [
  "All Tours",
  "Group Tours",
  "Family Tours",
  "Nature & Eco",
  "Geographical Expedition",
  "Birdwatching",
  "Corporate & MICE",
  "Yoga & Wellness",
  "School & College",
  "Honeymoon",
  "Weddings",
];

export const destinations = [
  { name: "Paro", desc: "Sacred valley, Taktsang & international gateway", image: tigersNest, slug: "paro" },
  { name: "Thimphu", desc: "Capital of a kingdom in the clouds", image: thimphu, slug: "thimphu" },
  { name: "Punakha", desc: "Former winter capital, dzong & river confluence", image: punakha, slug: "punakha" },
  { name: "Phobjikha", desc: "Glacial valley & black-necked crane habitat", image: bumthang, slug: "phobjikha" },
];

export const experiences = [
  { title: "Cultural Exchange & GNH", desc: "Heritage circuits, dzong studies and hands-on craft workshops with master artisans.", image: festival },
  { title: "Wellness & Meditation", desc: "Monastery retreats, daily guided practice and traditional hot-stone baths.", image: yoga },
  { title: "Nature, Birding & Conservation", desc: "Wetland walks, crane habitats and naturalist-guided forest trails.", image: birdwatching },
  { title: "Celebrations & Corporate", desc: "Destination weddings, gala dinners and tech-enabled executive retreats.", image: corporate },
];
