import tigersNest from "@/assets/tigers-nest.jpg";
import culture from "@/assets/culture.jpg";
import trekking from "@/assets/trekking.jpg";
import punakha from "@/assets/punakha.jpg";
import thimphu from "@/assets/thimphu.jpg";
import bumthang from "@/assets/bumthang.jpg";
import festival from "@/assets/festival.jpg";
import birdwatching from "@/assets/birdwatching.jpg";
import corporate from "@/assets/corporate.jpg";
import yoga from "@/assets/yoga.jpg";
import wedding from "@/assets/wedding.jpg";
import wildlife from "@/assets/wildlife.jpg";
import tropical from "@/assets/tropical.jpg";
import historical from "@/assets/historical.jpg";
import type { Tour } from "@/components/TourCard";

const commonExcludes = [
  "International / regional airfare",
  "Sustainable Development Fee (SDF) — collected directly by TCB",
  "Personal expenses, tips and travel insurance",
  "Any activity or meal not specified in the itinerary",
];

export const tours: Tour[] = [
  {
    slug: "group-tours-classic-bhutan-circuit",
    title: "Group Tour Package",
    category: "Group Tours",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha – Wangdue – Paro",
    location: "Paro · Thimphu · Punakha · Wangdue",
    price: 1290,
    image: punakha,
    desc: "A fixed-departure circuit using bulk hotel allocations and coach logistics to keep per-head costs competitive across Bhutan's essential highlights.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "March–May & September–November",
    groupSize: "15–40 pax, fixed departures",
    idealFor: "Travel-agent groups, cultural associations and large family reunions",
    overview:
      "Designed for fixed-departure groups, this circuit uses bulk hotel allocations and high-capacity coach logistics to keep per-head costs competitive without compromising on Bhutan's essential highlights. It is our most-booked format for travel-agent groups, cultural associations, and large family reunions. Trip grade: easy — coach-based sightseeing circuit.",
    highlights: [
      "Bulk-rate group hotel allocations for cost efficiency",
      "Optional cultural performance for groups of 20+",
      "High-capacity coach logistics across all destinations",
      "Fixed departure dates available for easy planning",
      "Dedicated group coordinator on call throughout",
      "Group photo stops built into the itinerary",
    ],
    includes: [
      "Group accommodation on twin-sharing basis with bulk allocation rates",
      "All meals throughout the tour",
      "High-capacity coach/vehicle and licensed guide(s) scaled to group size",
      "All monument and temple entrance fees, airport transfers",
      "Complimentary group coordinator for groups above 15 pax",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Group arrival at Paro International Airport and coach transfer to Thimphu. Evening group visit to the National Memorial Chorten and Changangkha Lhakhang. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu sightseeing", desc: "Buddha Dordenma, the Takin Preserve, Zorig Chusum Institute of Traditional Arts & Crafts, and the evening flag-lowering ceremony at Tashichho Dzong. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha, via Dochula Pass", desc: "Group photo stop at Dochula Pass among its 108 chortens, then on to Punakha Dzong and Chimi Lhakhang, the Fertility Temple. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha – Wangdue Phodrang", desc: "Visit Wangdue Phodrang Dzong and enjoy a group lunch at a local farmhouse, with an optional cultural performance for groups of 20+. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Return to Paro via Tamchog Lhakhang and its historic iron chain bridge. Evening at leisure or optional group dinner with folk dance performance. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang Monastery hike & departure", desc: "Group hike to Taktsang (Tiger's Nest) Monastery for early arrivals; group transfer to Paro International Airport for later departures." },
    ],
  },
  {
    slug: "family-tours",
    title: "Family Tour Package",
    category: "Family Tours",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha – Paro",
    location: "Paro · Thimphu · Punakha",
    price: 1690,
    image: culture,
    desc: "A gentler-paced circuit with private chauffeured transport, child- and elderly-friendly meal planning and extra flexibility built into each day.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "March–May & September–November",
    groupSize: "Private tour — any family size",
    idealFor: "Multi-generational families, travellers with children or elderly members",
    overview:
      "Family Tour Package is built at a gentler pace than our standard circuits, with private chauffeured transport, child- and elderly-friendly meal planning, and extra flexibility built into each day so no one in the group feels rushed. Trip grade: easy — relaxed pace with a private vehicle throughout.",
    highlights: [
      "Private vehicle — no shared transport with strangers",
      "Optional beginner rafting for older children",
      "Child- and elderly-friendly meal planning",
      "Family-configured rooms where available",
      "Relaxed daily pace with built-in rest stops",
      "Flexible sightseeing pace, no fixed group schedule",
    ],
    includes: [
      "Family-configured accommodation (connecting/triple rooms where available)",
      "All meals with child-friendly menu options",
      "Private chauffeured vehicle and licensed guide throughout",
      "All monument and temple entrance fees, airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Private transfer to Thimphu with rest stops as needed. Easy evening visit to the Centenary Farmers Market — a favourite with children for its sights and smells. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu family day", desc: "Visit the Takin Preserve to see Bhutan's national animal up close, the Changangkha Lhakhang (traditionally where families bring newborns for blessings), and easy walking at Buddha Dordenma's viewing terraces. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "A scenic, unhurried drive via Dochula Pass with a rest and photo stop among the chortens, continuing to Punakha Dzong at a relaxed pace. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha leisure day", desc: "Easy rice-paddy walk to Chimi Lhakhang, gentle riverside time by the Mo Chhu, and an optional short beginner rafting stretch for older children and adults. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Return drive to Paro with a stop at Tamchog Lhakhang's iron bridge. Free afternoon in Paro town for souvenir shopping. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang base visit & departure", desc: "Families may choose the full hike to Taktsang Monastery or a shorter walk to the cafeteria viewpoint, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "nature-and-eco-tours",
    title: "Nature & Eco Tours",
    category: "Nature & Eco",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Flora, Fauna & Conservation Trails",
    location: "Thimphu · Punakha · Phobjikha",
    price: 1490,
    image: bumthang,
    desc: "Conservation-led travel through Bhutan's forests, wetlands and glacial valleys with naturalist guides.",
    rating: 4.8,
    difficulty: "Moderate",
    bestTime: "Oct–Mar (crane season) · Apr–May (blooms)",
    groupSize: "2–12 pax, naturalist-guided",
    idealFor: "Nature lovers, eco-conscious travellers and small groups interested in Bhutan's conservation model",
    overview:
      "A conservation-focused circuit exploring Bhutan's forests, wetlands and protected valleys — from the Phobjikha black-necked crane habitat to rhododendron and magnolia trails — guided by trained naturalists.",
    highlights: [
      "Black-necked crane habitat visit in the Phobjikha wetlands",
      "Alpine meadow and rhododendron trails around Dochula Pass",
      "Community-based conservation and eco-lodge stays",
      "Naturalist-guided walks with species checklists",
      "Low-impact travel following Bhutan's carbon-negative model",
    ],
    includes: [
      "5 nights' accommodation in eco-lodges and guesthouses",
      "Daily breakfast, lunch and dinner",
      "Naturalist guide and private vehicle with driver",
      "All park entrance and conservation area fees",
      "SDF and visa processing assistance",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro Airport and private drive to Thimphu. Evening conservation briefing with your naturalist guide." },
      { day: 2, title: "Thimphu conservation circuit", desc: "Motithang Takin Preserve, the Royal Botanical Park and a forest walk covering Bhutan's endemic flora and protected species." },
      { day: 3, title: "Thimphu — Punakha via Dochula", desc: "Drive to Punakha over Dochula Pass with its 108 chortens and alpine meadow trail. Riverside birding in the Punakha valley." },
      { day: 4, title: "Phobjikha Valley — wetland conservation", desc: "Transfer to the glacial Phobjikha Valley. Visit the Black-Necked Crane Information Centre and walk the Gangtey Nature Trail among grazing yaks." },
      { day: 5, title: "Phobjikha — Paro", desc: "Morning wetland walk, then a scenic drive to Paro with panoramic Himalayan ridgeline stops along the way." },
      { day: 6, title: "Paro valley walk — departure", desc: "Kyichu Lhakhang and a final riverside valley walk before transfer to Paro International Airport." },
    ],
  },
  {
    slug: "geographical-expedition",
    title: "Geographical Expedition Package",
    category: "Geographical Expedition",
    duration: "8 Days",
    nights: "8 Days / 7 Nights",
    tagline: "Paro – Chele La – Haa Valley – Gasa – Punakha – Paro",
    location: "Paro · Haa · Gasa · Punakha",
    price: 1990,
    image: trekking,
    desc: "Led by a specialist guide briefed on sub-Himalayan thrust geology, crossing Chele La into the secluded Haa Valley and on to remote Gasa.",
    rating: 4.8,
    difficulty: "Moderate to Challenging",
    bestTime: "April–June & September–November",
    groupSize: "Small groups, 4x4 supported",
    idealFor: "Geography and geology enthusiasts, offbeat explorers",
    overview:
      "Led by a local specialist guide briefed on the region's sub-Himalayan thrust geology, this expedition crosses Chele La — one of Bhutan's highest motorable passes — into the secluded Haa Valley, then continues to remote Gasa, ending with a soak in its medicinal hot springs (tshachu). Trip grade: moderate to challenging — remote roads and guided field walks.",
    highlights: [
      "Local geology briefing throughout the route",
      "4x4 vehicle for remote, less-travelled roads",
      "Crosses Chele La, one of Bhutan's highest passes",
      "Farmhouse stays for authentic local immersion",
      "Soak in the medicinal Gasa hot springs (tshachu)",
      "Visits Bhutan's least-visited dzongkhags",
    ],
    includes: [
      "All accommodation on twin-sharing basis (farmhouse stays where hotels are unavailable)",
      "All meals throughout the tour",
      "Licensed guide with regional geography briefing materials, private 4x4 vehicle with driver",
      "Gasa hot springs (tshachu) entry, all monument and temple entrance fees",
      "Airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro", desc: "Arrival, hotel check-in, and afternoon visit to Rinpung Dzong. Evening expedition briefing. Overnight at hotel, Paro." },
      { day: 2, title: "Paro – Chele La Pass – Haa Valley", desc: "Cross Chele La Pass (3,988m) with views of Jomolhari and Jichu Drake on clear days, descending into the remote Haa Valley, opened to tourism only in 2002. Visit the twin temples of Lhakhang Karpo and Lhakhang Nagpo. Overnight at hotel/farmhouse, Haa." },
      { day: 3, title: "Haa Valley geological walk", desc: "A guided walk through Haa's pastoral villages, discussing the region's distinctive slate and stone architecture and underlying geology. Overnight at hotel/farmhouse, Haa." },
      { day: 4, title: "Haa – Punakha (transit)", desc: "Scenic transit day back through Paro and over Dochula Pass toward Punakha. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Gasa", desc: "Drive north along the Mo Chhu river valley into Gasa Dzongkhag, Bhutan's most sparsely populated district, visiting Gasa Dzong. Overnight at hotel, Gasa." },
      { day: 6, title: "Gasa hot springs (tshachu) & geological walk", desc: "Morning guided walk through the forest surrounding Gasa with your naturalist guide, followed by an afternoon soak in the Gasa Tshachu hot springs beside the Mo Chhu river. Overnight at hotel, Gasa." },
      { day: 7, title: "Gasa – Punakha – Paro", desc: "Return through Punakha, visiting Punakha Dzong, before continuing to Paro via Dochula Pass. Overnight at hotel, Paro." },
      { day: 8, title: "Departure", desc: "Transfer to Paro International Airport for your onward flight." },
    ],
  },
  {
    slug: "historical-tours",
    title: "Historical Tours",
    category: "Historical",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Dzongs, Fortresses & Royal Heritage",
    location: "Paro · Thimphu · Punakha",
    price: 1350,
    image: historical,
    desc: "A deep dive into Bhutan's architectural and dynastic history — from 17th-century fortress-monasteries to royal heritage sites — narrated by specialist historical guides.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Sep–Nov · Mar–May",
    groupSize: "2–16 pax with a specialist historical guide",
    idealFor: "History enthusiasts, heritage travellers and cultural researchers",
    overview:
      "A deep dive into Bhutan's architectural and dynastic history. The circuit moves from 17th-century fortress-monasteries to royal heritage sites and national museum collections, narrated throughout by a specialist historical guide.",
    highlights: [
      "Visits every major dzong along the western corridor",
      "In-depth narration on the unification of Bhutan and the dynastic timeline",
      "Museum-led sessions at the National Museum of Bhutan",
      "Drugyal Dzong ruins and their place in Bhutanese military history",
      "Culminates with the Taktsang Monastery pilgrimage",
    ],
    includes: [
      "5 nights' accommodation in heritage-style hotels",
      "Daily breakfast, lunch and dinner",
      "Specialist historical guide and private vehicle with driver",
      "Entrance fees to all dzongs, museums and heritage sites",
      "SDF and visa processing assistance",
      "Printed historical booklet and route notes",
    ],
    excludes: [...commonExcludes, "Photography permits inside restricted museum galleries", "Pony rental for the Taktsang hike (optional)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro International Airport and private drive to Thimphu. Evening orientation on Bhutan's dynastic timeline. Overnight in Thimphu." },
      { day: 2, title: "Thimphu historical sites", desc: "National Memorial Chorten, Tashichho Dzong, the National Library's ancient manuscripts and a museum-led session at the Folk Heritage Museum. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha via Dochula Pass", desc: "Drive over Dochula Pass to Punakha. In-depth tour of Punakha Dzong, seat of Bhutan's first coronation, and a crossing of the longest suspension bridge in Bhutan. Overnight in Punakha." },
      { day: 4, title: "Punakha — Wangdue Phodrang", desc: "Wangdue Phodrang Dzong and Chimi Lhakhang, with a session on regional governance and fortress architecture. Overnight in Punakha." },
      { day: 5, title: "Paro historical circuit", desc: "Return to Paro for Rinpung Dzong, the National Museum at Ta Dzong and the Drugyal Dzong ruins. Overnight in Paro." },
      { day: 6, title: "Taktsang Monastery — departure", desc: "Morning hike to Taktsang Monastery, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "wildlife-safari",
    title: "Wildlife Safari",
    category: "Wildlife",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Rare Species & Conservation Encounters",
    location: "Paro · Thimphu · Punakha · Phobjikha",
    price: 1690,
    image: wildlife,
    desc: "Focused itineraries targeting Bhutan's rare and endangered species, from the majestic takin to the black-necked crane, guided by wildlife specialists across protected conservation zones.",
    rating: 4.9,
    difficulty: "Moderate",
    bestTime: "Nov–Feb (black-necked crane) · year-round for takin",
    groupSize: "2–12 pax with a wildlife specialist guide",
    idealFor: "Wildlife photographers, conservationists and nature travellers",
    overview:
      "Focused itineraries targeting Bhutan's rare and endangered species — the golden takin, black-necked crane and Himalayan monal among them — guided by wildlife specialists across the Kingdom's protected conservation zones.",
    highlights: [
      "Targets flagship species: golden takin, black-necked crane and Himalayan monal",
      "Access to Phobjikha valley's protected crane wintering grounds",
      "Explores Bhutan's protected-area network and conservation policy",
      "Optional extension to Royal Manas National Park (quoted separately)",
      "Dedicated wildlife-photography review session",
    ],
    includes: [
      "6 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Wildlife specialist guide, spotting-scope access and private vehicle",
      "Entrance fees and protected-area permit assistance",
      "SDF and visa processing assistance",
      "Species checklist and field guide booklet",
    ],
    excludes: [...commonExcludes, "Royal Manas National Park extension (quoted separately on request)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Arrival briefing on Bhutan's protected-area network, with a first look for Himalayan griffon over the Paro valley. Overnight in Thimphu." },
      { day: 2, title: "Thimphu wildlife circuit", desc: "Motithang Takin Preserve for Bhutan's national animal, followed by forest-edge birding and a conservation briefing. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha", desc: "Drive to Punakha with wildlife stops en route; afternoon river-otter and riverine habitat watch along the Mo Chhu. Overnight in Punakha." },
      { day: 4, title: "Phobjikha valley — black-necked crane", desc: "Full day dedicated to Phobjikha, including the Black-Necked Crane Centre and cranes feeding in the valley marshland. Overnight in Phobjikha." },
      { day: 5, title: "Phobjikha — Paro", desc: "Return towards Paro with forest-trail stops for Himalayan monal and pheasant species in temperate forest. Overnight in Paro." },
      { day: 6, title: "Paro valley wildlife walk", desc: "Early morning wildlife walk near Kyichu Lhakhang and the Paro river corridor for valley birdlife at dawn. Overnight in Paro." },
      { day: 7, title: "Departure", desc: "Sunrise over the Paro valley, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "tropical-expedition",
    title: "Tropical Expedition",
    category: "Tropical Expedition",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Subtropical Southern Bhutan",
    location: "Paro · Thimphu · Phuentsholing · Punakha",
    price: 1290,
    image: tropical,
    desc: "An offbeat itinerary into Bhutan's lesser-visited subtropical south — humid lowland forests, border towns and a striking contrast to the alpine north.",
    rating: 4.7,
    difficulty: "Easy",
    bestTime: "Nov–Feb (dry, comfortable lowland temperatures)",
    groupSize: "2–16 pax",
    idealFor: "Offbeat travellers wanting to see beyond the typical alpine circuit",
    overview:
      "An offbeat itinerary into Bhutan's lesser-visited subtropical south — humid lowland forests, border towns and tropical gardens — offering a striking contrast to the alpine north for travellers seeking a different side of the Kingdom.",
    highlights: [
      "One of the few itineraries to include Phuentsholing in southern Bhutan",
      "Visits the Crocodile Breeding Centre at Phuentsholing",
      "Traverses dramatic climatic transitions from alpine to subtropical zones",
      "Kharbandi Monastery's tropical gardens overlooking the southern plains",
      "Scenic descent and ascent drives through Bhutan's foothill forests",
    ],
    includes: [
      "5 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Licensed guide and private vehicle with driver",
      "Entrance fees to all sites listed in the itinerary",
      "SDF and visa processing assistance",
      "Border-town permit coordination",
    ],
    excludes: [...commonExcludes, "Any cross-border excursion into India"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro International Airport and drive to Thimphu. Evening at leisure with a Bhutanese welcome dinner. Overnight in Thimphu." },
      { day: 2, title: "Thimphu — descent to Phuentsholing", desc: "Long, scenic descent through foothill forest as the climate shifts from temperate to subtropical. Overnight in Phuentsholing." },
      { day: 3, title: "Phuentsholing & southern foothills", desc: "Kharbandi Monastery gardens overlooking the southern plains, the Crocodile Breeding Centre and the Zangtho Pelri Lhakhang. Overnight in Phuentsholing." },
      { day: 4, title: "Phuentsholing — Punakha", desc: "Return ascent through central Bhutan, arriving in the Punakha valley by evening. Overnight in Punakha." },
      { day: 5, title: "Punakha — Paro", desc: "Punakha Dzong and Chimi Lhakhang in the morning, then a scenic drive back to Paro. Afternoon at leisure in Paro town. Overnight in Paro." },
      { day: 6, title: "Departure", desc: "Transfer to Paro International Airport with a farewell keepsake from Golden Takin Holidays." },
    ],
  },
  {
    slug: "buddhist-culture-tours",
    title: "Buddhist Culture & Historical Tour Package",
    category: "Buddhist Culture",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha – Wangdue – Gasa – Paro",
    location: "Paro · Thimphu · Punakha · Gasa",
    price: 1490,
    image: culture,
    desc: "A deep cultural submersion into Bhutan's living Buddhist heritage, tracing five major dzongs and sacred temples across the western valleys.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "March–May & September–November",
    groupSize: "2–16 pax",
    idealFor: "Cultural historians, pilgrims and heritage travellers",
    overview:
      "This tour is a deep cultural submersion into Bhutan's living Buddhist heritage, tracing five major dzongs and sacred temples across the western valleys — from Thimphu's seat of government to remote Gasa, one of the least-visited fortress-monasteries in the country. Trip grade: easy — temple and dzong visits with a licensed cultural guide.",
    highlights: [
      "Visits five major dzongs across three valleys",
      "Guided history session on Bhutan's 17th-century unification",
      "Licensed cultural/historical guide throughout",
      "Visits the Zorig Chusum Institute of Traditional Arts",
      "Includes remote Gasa Dzong, rarely visited by tourists",
      "Pilgrimage hike to Taktsang Monastery",
    ],
    includes: [
      "All accommodation on twin-sharing basis",
      "All meals throughout the tour",
      "Licensed cultural/historical guide and private vehicle with driver",
      "All monument, museum and temple entrance fees, airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening visit to the National Memorial Chorten and Changangkha Lhakhang. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu heritage sites", desc: "Visit Tashichho Dzong, Simtokha Dzong (one of Bhutan's oldest fortresses, built in 1629), and the Zorig Chusum Institute of Traditional Arts & Crafts. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass and its 108 memorial chortens, then visit Punakha Dzong, built in 1637 at the confluence of the Pho Chhu and Mo Chhu rivers, and Chimi Lhakhang. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha – Wangdue Phodrang", desc: "Visit Wangdue Phodrang Dzong, perched on a ridge above the Punakha valley, and the nearby weaving village of Rinchengang. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Gasa", desc: "Drive north along the Mo Chhu river valley to Gasa Dzong, a 17th-century fortress built to defend against Tibetan invasions and rarely visited by international tourists. Overnight at hotel, Gasa." },
      { day: 6, title: "Gasa – Paro", desc: "Return south via Punakha and Dochula Pass to Paro, stopping at Tamchog Lhakhang and Kyichu Lhakhang, one of Bhutan's oldest temples. Overnight at hotel, Paro." },
      { day: 7, title: "Taktsang Monastery hike & departure", desc: "Hike to Taktsang (Tiger's Nest) Monastery, Bhutan's most sacred pilgrimage site, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "hiking-and-trekking",
    title: "Hiking & Trekking Package",
    category: "Hiking & Trekking",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Druk Path Trek · Paro – Thimphu",
    location: "Paro · Druk Path Trek · Thimphu",
    price: 1750,
    image: trekking,
    desc: "Built around the Druk Path — Bhutan's classic entry-level trek connecting Paro and Thimphu through a chain of alpine lakes and meditation retreats.",
    rating: 4.9,
    difficulty: "Moderate — high-altitude camping trek, max altitude ~4,100m",
    bestTime: "March–June & September–November",
    groupSize: "Small trek groups with full camping crew",
    idealFor: "Beginner-to-intermediate trekkers wanting a genuine camping trek",
    overview:
      "Our Hiking & Trekking Package is built around the Druk Path — Bhutan's classic entry-level trek connecting Paro and Thimphu through a chain of alpine lakes and meditation retreats. Backed by full camping logistics and an experienced trek crew, it's the ideal introduction to high-altitude trekking in the Himalayas. Longer expeditions (Jomolhari Trek, Snowman Trek) are available on request for experienced trekkers.",
    highlights: [
      "Full camping support: tents, cook crew, pack horses",
      "Visits Jili Dzong and Phajoding meditation retreats",
      "Beginner-friendly high-altitude introduction",
      "Small trek groups for a genuine wilderness feel",
      "Panoramic views of Jomolhari & Jichu Drake",
      "Extension available to Jomolhari or Snowman Trek",
    ],
    includes: [
      "Hotel accommodation (Paro/Thimphu) and full camping setup during the trek",
      "All meals throughout, including trek-side cooked meals",
      "Licensed guide, trek crew, and pack horses for equipment",
      "All entrance fees and airport transfers",
    ],
    excludes: [
      "International and domestic airfare",
      "Sustainable Development Fee (SDF), collected directly by TCB",
      "Personal trekking gear (sleeping bag rental available on request), travel insurance",
      "Bhutan visa fee, tips and personal expenses",
    ],
    itinerary: [
      { day: 1, title: "Arrive Paro", desc: "Arrival, hotel check-in, and afternoon visit to Rinpung Dzong. Evening trek briefing and equipment check. Overnight at hotel, Paro." },
      { day: 2, title: "Trek Day 1 — Ta Dzong to Jili Dzong", desc: "Climb through blue pine and rhododendron forest to Jili Dzong (3,480m), a former meditation retreat with views over the Paro valley. Overnight camping, Jili Dzong." },
      { day: 3, title: "Trek Day 2 — Jili Dzong to Jangchulakha", desc: "A ridge walk with views of Jomolhari and Jichu Drake on clear days, through dwarf rhododendron and seasonal yak-herder camps. Overnight camping, Jangchulakha." },
      { day: 4, title: "Trek Day 3 — Jangchulakha to Jimilangtsho Lake", desc: "Continue along the ridge to Jimilangtsho, a glacial lake known for its giant trout — a shorter, more relaxed trekking day. Overnight camping, Jimilangtsho." },
      { day: 5, title: "Trek Day 4 — Jimilangtsho to Phajoding, descend to Thimphu", desc: "Trek past Simkotra Lake to Phajoding Monastery overlooking the Thimphu valley, then descend to the trailhead and transfer into the city. Overnight at hotel, Thimphu." },
      { day: 6, title: "Thimphu Sightseeing & Departure", desc: "Visit Tashichho Dzong and the Takin Preserve before transferring to Paro International Airport for your onward flight." },
    ],

  },
  {
    slug: "birdwatching-tours",
    title: "Birdwatching Tours",
    category: "Birdwatching",
    duration: "8 Days",
    nights: "8 Days / 7 Nights",
    tagline: "Ornithology Expedition",
    location: "Paro · Thimphu · Punakha · Phobjikha",
    price: 1890,
    image: birdwatching,
    desc: "An expertly guided itinerary targeting Bhutan's avian diversity, from the elusive Ward's Trogon to the endangered Black-Necked Crane.",
    rating: 4.9,
    difficulty: "Moderate",
    bestTime: "Mar–May · Oct–Nov (peak migration)",
    groupSize: "Small groups with expert ornithologist guide",
    idealFor: "Ornithologists and avid birders",
    overview:
      "A highly focused, expertly guided itinerary designed for ornithology enthusiasts, targeting Bhutan's diverse avian species — from the elusive Ward's Trogon to the endangered Black-Necked Crane — with stops at key birding hotspots.",
    highlights: [
      "Expert ornithologist guide throughout",
      "High-altitude birding across Lawa La and Dochula",
      "Riverine species sightings in the Punakha valley",
      "Black-Necked Crane habitat visit in Phobjikha",
      "Species checklist provided and daily briefings",
    ],
    includes: [
      "All accommodation on twin-sharing basis including a retreat lodge stay in Punakha",
      "All meals (vegetarian options available throughout)",
      "Licensed ornithologist guide and private vehicle with driver",
      "All entrance fees and airport transfers",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Optics rental"],
    itinerary: [
      { day: 1, title: "Arrival — transfer to Thimphu", desc: "Evening birding checklist briefing. Overnight in hotel, Thimphu." },
      { day: 2, title: "Thimphu to Punakha via Lawa La", desc: "Target high-altitude species such as Satyr Tragopan along the pass. Overnight in hotel, Punakha." },
      { day: 3, title: "Punakha — Jigme Dorji National Park", desc: "Riverside birding for Ibisbill and riverine specialists. Overnight in hotel, Punakha." },
      { day: 4, title: "Punakha to Phobjikha", desc: "Drive through temperate forest for Ward's Trogon, then descend to the valley wetlands. Overnight in guesthouse, Phobjikha." },
      { day: 5, title: "Phobjikha full-day birding", desc: "Black-Necked Crane habitat and wetland circuit with the Gangtey ridge forest edge." },
      { day: 6, title: "Phobjikha to Paro", desc: "Return journey with final birding stops en route. Overnight in hotel, Paro." },
      { day: 7, title: "Paro valley & Taktsang trail birding", desc: "Early morning birding on the Tiger's Nest trail and along the Paro Chhu." },
      { day: 8, title: "Departure", desc: "Final checklist review and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "corporate-meetups-mice",
    title: "Corporate MICE Package",
    category: "Corporate & MICE",
    duration: "5 Days",
    nights: "5 Days / 4 Nights",
    tagline: "Thimphu – Paro",
    location: "Thimphu · Paro",
    price: 1390,
    image: corporate,
    desc: "Full-scale execution of off-site corporate programs, combining tech-enabled conference venues with Bhutan's cultural backdrop.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Year-round (Oct–Apr recommended for indoor conference use)",
    groupSize: "Scalable to any company size",
    idealFor: "Corporate off-sites, leadership retreats, seminars and product launches",
    overview:
      "Corporate MICE Package delivers full-scale execution of off-site corporate programs in Thimphu and Paro, combining tech-enabled conference venues with Bhutan's cultural backdrop for team-building activities, gala dinners, and leadership retreats. Programs are customised per company size and objectives; the below is an indicative 5-day format.",
    highlights: [
      "Tech-enabled conference venues in Thimphu & Paro",
      "Dedicated corporate account manager",
      "Facilitated team-building activities",
      "Scalable to any company size or objective",
      "One customised gala dinner included",
      "Cultural excursions built around the work schedule",
    ],
    includes: [
      "Conference venue hire with standard AV/tech setup",
      "All accommodation on twin-sharing or single-occupancy basis (as required)",
      "All meals, working lunches, and one gala dinner",
      "Team-building activity facilitation and dedicated corporate account manager",
      "Private vehicle fleet and licensed guide(s), airport transfers",
    ],
    excludes: [
      "International and domestic airfare",
      "Sustainable Development Fee (SDF), collected directly by TCB",
      "Bhutan visa fee, travel insurance",
      "Custom branding/signage and specialised AV equipment beyond standard setup (quoted separately)",
    ],
    itinerary: [
      { day: 1, title: "Arrive Thimphu", desc: "Arrival and transfer to Thimphu. Evening welcome reception and program briefing with your dedicated corporate account manager. Overnight at hotel, Thimphu." },
      { day: 2, title: "Conference day 1", desc: "Full-day seminar/conference sessions at a tech-enabled venue in Thimphu, with coffee breaks and a working lunch arranged on-site. Overnight at hotel, Thimphu." },
      { day: 3, title: "Team-building & cultural immersion", desc: "Morning team-building activities (archery challenge, treasure hunt through Thimphu's landmarks), afternoon visit to Tashichho Dzong and Buddha Dordenma. Overnight at hotel, Thimphu." },
      { day: 4, title: "Thimphu – Paro, conference day 2 & gala dinner", desc: "Transfer to Paro for the closing session, followed by a customised gala dinner with traditional Bhutanese entertainment. Overnight at hotel, Paro." },
      { day: 5, title: "Departure", desc: "Optional morning excursion to Taktsang Monastery viewpoint for early arrivals, followed by transfer to Paro International Airport." },
    ],
  },
  {
    slug: "yoga-and-meditation-tours",
    title: "Yoga & Meditation Package",
    category: "Yoga & Wellness",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha",
    location: "Paro · Thimphu · Punakha",
    price: 1790,
    image: yoga,
    desc: "A slower, retreat-paced itinerary at monastery-affiliated retreat centres and riverside wellness lodges, with daily sessions led by local Buddhist masters.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Small retreat groups",
    idealFor: "Wellness travellers, meditation practitioners and digital-detox seekers",
    overview:
      "A slower, retreat-paced itinerary hosted at monastery-affiliated retreat centres and riverside wellness lodges, with daily meditation and yoga sessions led by local Buddhist masters, interspersed with gentle sightseeing. Trip grade: easy — retreat-paced with daily sessions.",
    highlights: [
      "Daily sessions led by a local Buddhist master",
      "Slow, retreat-paced schedule",
      "Riverside retreat lodge stay in Punakha",
      "Mindful walk among Dochula Pass's 108 chortens",
      "Vegetarian meal options throughout",
      "Optional spa treatment in Paro",
    ],
    includes: [
      "All accommodation on twin-sharing basis, including retreat lodge stay in Punakha",
      "All meals (vegetarian options available throughout)",
      "Daily yoga/meditation sessions led by a local Buddhist master",
      "Licensed guide and private vehicle with driver, all entrance fees",
      "Airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening grounding meditation session to settle in after travel. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu retreat day", desc: "Morning meditation session led by a local master, followed by an easy visit to Buddha Dordenma and the Takin Preserve. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass with a mindful walk among the 108 chortens, continuing to a riverside retreat lodge in Punakha. Overnight at retreat lodge, Punakha." },
      { day: 4, title: "Punakha yoga & meditation day", desc: "A full wellness day: morning yoga overlooking the Mo Chhu river, an afternoon visit to Chimi Lhakhang, and an evening guided meditation session. Overnight at retreat lodge, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Gentle drive back to Paro via Tamchog Lhakhang. Free afternoon for quiet reflection or a spa treatment. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang pilgrimage & departure", desc: "A mindful hike to Taktsang (Tiger's Nest) Monastery, one of Buddhism's holiest sites, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "school-college-cultural-exchange",
    title: "School & College Cultural Exchange Package",
    category: "School & College",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha",
    location: "Thimphu · Punakha · Paro",
    price: 1150,
    image: festival,
    desc: "A structured educational circuit focused on Gross National Happiness, sustainable architecture and Bhutanese history, designed with institutional partners.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "October–April (school term-friendly)",
    groupSize: "Student groups, ages 14–22",
    idealFor: "CBSE/ICSE schools, colleges and student groups",
    overview:
      "A structured educational circuit for schools and colleges, focused on Gross National Happiness (GNH), sustainable architecture, and Bhutanese history — designed in coordination with institutional partners as part of Golden Takin Holidays' education desk. Trip grade: easy — structured educational circuit with group supervision.",
    highlights: [
      "Structured GNH and governance learning sessions",
      "Certificate of completion for participating students",
      "Dedicated education-desk coordinator",
      "Village homestay-style community interaction",
      "Group supervision rooms for accompanying staff",
      "Cultural quiz and closing ceremony",
    ],
    includes: [
      "Group accommodation on multi-share basis with dedicated supervision rooms for accompanying staff",
      "All meals throughout the tour",
      "Licensed educational guide(s) and private coach/vehicles scaled to group size",
      "All monument and temple entrance fees, structured learning sessions",
      "Airport transfers and a dedicated education-desk coordinator",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Group arrival and transfer to Thimphu. Evening orientation session on Bhutanese culture and etiquette. Overnight at hotel, Thimphu." },
      { day: 2, title: "GNH & governance study day", desc: "Visit to Tashichho Dzong, seat of the Bhutanese government, with an educational session on the Gross National Happiness development philosophy. Overnight at hotel, Thimphu." },
      { day: 3, title: "Traditional arts & sustainable architecture", desc: "Visit the Zorig Chusum Institute of Traditional Arts & Crafts, the Paper Factory, and a briefing on traditional rammed-earth and timber construction techniques still used across Bhutan. Overnight at hotel, Thimphu." },
      { day: 4, title: "Thimphu – Punakha, history day", desc: "Cross Dochula Pass and visit Punakha Dzong, with a guided historical session on the Zhabdrung's unification of Bhutan in the 17th century. Overnight at hotel, Punakha." },
      { day: 5, title: "Community & environment day", desc: "Village walk and interaction with a local farming family, plus an environmental briefing on Bhutan's constitutionally mandated forest cover and conservation policy. Overnight at hotel, Punakha." },
      { day: 6, title: "Punakha – Paro", desc: "Return to Paro via Tamchog Lhakhang. Evening student reflection session and cultural quiz. Overnight at hotel, Paro." },
      { day: 7, title: "Taktsang hike & departure", desc: "Group hike to Taktsang Monastery, followed by a closing ceremony and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "honeymoon-trips",
    title: "Honeymoon Package",
    category: "Honeymoon",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha – Paro",
    location: "Paro · Thimphu · Punakha",
    price: 2190,
    image: tigersNest,
    desc: "A romantic-paced journey through Bhutan's most scenic valleys, with private candlelit dinners, couple's spa time and quiet moments built into each day.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Private — exclusively for the couple",
    idealFor: "Newlyweds and couples seeking a romantic getaway",
    overview:
      "Honeymoon Package is a romantic-paced journey through Bhutan's most scenic valleys, with private candlelit dinners, couple's spa time, and quiet moments built into each day — without the scale of a full destination wedding production. Trip grade: easy — leisure paced with private experiences.",
    highlights: [
      "One private candlelit dinner included",
      "Flexible pacing — nothing feels rushed",
      "Couple's spa session at a partner hotel",
      "Riverside hotel stay in Punakha",
      "Private vehicle and guide exclusively for you",
      "Optional private cultural performance",
    ],
    includes: [
      "Accommodation in couple-oriented rooms/suites where available",
      "All meals, including one private candlelit dinner",
      "Private vehicle with driver and licensed guide throughout",
      "All monument and temple entrance fees, airport transfers",
      "One couple's spa session (subject to hotel availability)",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Private welcome and transfer to Thimphu. Evening visit to the National Memorial Chorten at dusk, followed by a private welcome dinner. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu sightseeing", desc: "Visit Buddha Dordenma and Tashichho Dzong for the evening flag ceremony. Afternoon free for couple's spa treatments. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass together and visit Chimi Lhakhang, the Fertility Temple, considered especially auspicious for couples. Check into a riverside hotel overlooking the Mo Chhu. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha romantic day", desc: "Visit Punakha Dzong, then enjoy a private riverside picnic lunch. Evening candlelit dinner arranged on your hotel terrace. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Return to Paro via Tamchog Lhakhang. Afternoon at leisure, with an optional private cultural performance in the evening. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang couple's hike & departure", desc: "Hike together to Taktsang (Tiger's Nest) Monastery, followed by a private lunch with valley views, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "himalayan-wedding-ceremonies",
    title: "Destination Wedding Package",
    category: "Weddings",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha – Paro",
    location: "Paro · Thimphu · Punakha",
    price: 2890,
    image: wedding,
    desc: "Our full-production offering — venue selection, monk blessings, traditional attire, photography and every ceremonial detail coordinated end to end.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Couples and guest parties",
    idealFor: "Couples hosting a wedding or vow-renewal ceremony in Bhutan",
    overview:
      "Destination Wedding Package is our full-production offering: Golden Takin Holidays coordinates venue selection, monk blessings, traditional attire, photography, and every ceremonial detail, using premium hotel and resort partners such as Uma Paro, Amankora, and Six Senses Bhutan. Trip grade: easy — leisure paced with a full ceremony production day.",
    highlights: [
      "Dedicated wedding coordinator from Day 1",
      "Choice of premium resort partners",
      "Traditional Marchang blessing ceremony",
      "Archery demonstration and folk performance evening",
      "Professional photography & videography included",
      "Keepsake farewell gift on departure",
    ],
    includes: [
      "Accommodation on the selected circuit (premium/luxury options available)",
      "Dedicated wedding coordinator and full ceremony planning",
      "Traditional attire hire, monk blessing ceremony and Marchang ritual",
      "Professional photography and videography",
      "All meals, private vehicle with driver, and licensed guide",
      "Airport transfers",
    ],
    excludes: [
      "International and domestic airfare",
      "Sustainable Development Fee (SDF), collected directly by TCB",
      "Bhutan visa fee, travel insurance",
      "Guest list travel costs beyond the couple (quoted separately for group bookings)",
    ],
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening welcome dinner with your dedicated wedding coordinator to confirm ceremony arrangements. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu sightseeing & ceremony planning", desc: "Visit Buddha Dordenma and Tashichho Dzong, then meet with monks for a pre-wedding blessing consultation. Fitting for traditional Bhutanese wedding attire (gho and kira). Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Drive to Punakha via Dochula Pass. Visit Chimi Lhakhang, the Fertility Temple, before checking into a riverside venue overlooking the Mo Chhu. Overnight at hotel, Punakha." },
      { day: 4, title: "Wedding ceremony day", desc: "The ceremony opens with a traditional Marchang libation ritual and monk blessings, followed by the exchange of vows against a Punakha Dzong or riverside backdrop. Evening celebratory dinner with archery demonstrations and folk performances. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Leisurely drive back to Paro via Tamchog Lhakhang. Afternoon at leisure — spa treatments available. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang couple's hike", desc: "Hike together to Taktsang Monastery, followed by a private picnic lunch. Evening farewell dinner and photo album handover. Overnight at hotel, Paro." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport, with a keepsake gift from Golden Takin Holidays." },
    ],
  },
];

export const categories = [
  "All Tours",
  "Group Tours",
  "Family Tours",
  "Nature & Eco",
  "Geographical Expedition",
  "Historical",
  "Wildlife",
  "Tropical Expedition",
  "Buddhist Culture",
  "Hiking & Trekking",
  "Birdwatching",
  "Corporate & MICE",
  "Yoga & Wellness",
  "School & College",
  "Honeymoon",
  "Weddings",
];

export const destinations = [
  { name: "Paro", desc: "Sacred valley, Taktsang & international gateway", image: tigersNest, slug: "paro" },
  { name: "Thimphu", desc: "Capital of a kingdom in the clouds", image: thimphu, slug: "thimphu" },
  { name: "Punakha", desc: "Former winter capital, dzong & river confluence", image: punakha, slug: "punakha" },
  { name: "Phobjikha", desc: "Glacial valley & black-necked crane habitat", image: bumthang, slug: "phobjikha" },
];

export const experiences = [
  { title: "Cultural Exchange & GNH", desc: "Heritage circuits, dzong studies and hands-on craft workshops with master artisans.", image: festival },
  { title: "Wellness & Meditation", desc: "Monastery retreats, daily guided practice and traditional hot-stone baths.", image: yoga },
  { title: "Nature, Birding & Conservation", desc: "Wetland walks, crane habitats and naturalist-guided forest trails.", image: birdwatching },
  { title: "Celebrations & Corporate", desc: "Destination weddings, gala dinners and tech-enabled executive retreats.", image: corporate },
];
