import tigersNest from "@/assets/tigers-nest.jpg";
import culture from "@/assets/culture.jpg";
import trekking from "@/assets/trekking.jpg";
import punakha from "@/assets/punakha.jpg";
import thimphu from "@/assets/thimphu.jpg";
import bumthang from "@/assets/bumthang.jpg";
import festival from "@/assets/festival.jpg";
import birdwatching from "@/assets/birdwatching.jpg";
import corporate from "@/assets/corporate.jpg";
import yoga from "@/assets/yoga.jpg";
import wedding from "@/assets/wedding.jpg";
import wildlife from "@/assets/wildlife.jpg";
import tropical from "@/assets/tropical.jpg";
import historical from "@/assets/historical.jpg";
import type { Tour } from "@/components/TourCard";

const commonExcludes = [
  "International / regional airfare",
  "Sustainable Development Fee (SDF) — collected directly by TCB",
  "Personal expenses, tips and travel insurance",
  "Any activity or meal not specified in the itinerary",
];

export const tours: Tour[] = [
  {
    slug: "group-tours-classic-bhutan-circuit",
    title: "Group Tours — Classic Bhutan Circuit",
    category: "Group Tours",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Classic Bhutan Circuit",
    location: "Paro · Thimphu · Punakha",
    price: 1290,
    image: punakha,
    desc: "A fixed-departure circuit for groups of 15–40 pax combining bulk hotel allocations, coach logistics and Bhutan's most iconic sights.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "15–40 pax",
    idealFor: "B2B group blocks, school/corporate delegations and fixed-departure travellers",
    overview:
      "Designed for fixed-departure groups of 15–40 pax, this circuit combines bulk hotel allocations and high-capacity coach logistics with Bhutan's most iconic sights. It is the flagship itinerary for B2B agents and school/corporate blocks travelling together.",
    highlights: [
      "Covers all four flagship destinations — Thimphu, Punakha and Paro — in a proven circuit",
      "Optimised for bulk hotel allocation and high-capacity coach logistics",
      "Includes the iconic Taktsang (Tiger's Nest) hike, Bhutan's most photographed excursion",
      "Dedicated Golden Takin Holidays tour leader throughout the journey",
      "Farewell cultural evening with traditional mask-dance performance",
    ],
    includes: [
      "5 nights' accommodation on twin-sharing basis (3★ to 4★ category)",
      "Daily breakfast, lunch & dinner (Bhutanese/Continental/Indian options)",
      "All ground transport in private coach with English/Hindi-speaking licensed guide",
      "Entrance fees to all monuments & museums listed in itinerary",
      "SDF processing assistance",
      "Bhutan visa/permit processing",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Paro International Airport arrival. Private coach transfer to Thimphu (1 hr). Evening visit to Tashichho Dzong and a stroll through Thimphu town. Overnight in Thimphu." },
      { day: 2, title: "Thimphu sightseeing", desc: "Full day covering Buddha Dordenma Statue, Motithang Takin Preserve, National Memorial Chorten and the Institute of Zorig Chusum. Group photo session at the dzong courtyard. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha via Dochula Pass", desc: "Scenic drive to Punakha via Dochula Pass (3,100m) with panoramic Himalayan views among the 108 memorial chortens. Afternoon visit to Punakha Dzong at the confluence of Pho Chhu and Mo Chhu. Overnight in Punakha." },
      { day: 4, title: "Punakha — Paro", desc: "Morning walk to Chimi Lhakhang through rice terraces, followed by the scenic drive back to Paro. Evening at leisure to explore Paro town's traditional shopfronts and handicraft stalls. Overnight in Paro." },
      { day: 5, title: "Hike to Taktsang (Tiger's Nest) Monastery", desc: "Signature group excursion — guided hike (round trip approx. 5 hrs) to Taktsang Monastery perched at 3,120m. Group lunch at the cafeteria with valley views. Farewell dinner with cultural mask-dance performance. Overnight in Paro." },
      { day: 6, title: "Departure", desc: "Transfer to Paro International Airport for onward journey. Golden Takin Holidays representatives assist with group check-in." },
    ],
  },
  {
    slug: "family-tours",
    title: "Family Tours",
    category: "Family Tours",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Multi-Generational Bhutan Discovery",
    location: "Paro · Thimphu · Punakha",
    price: 1690,
    image: culture,
    desc: "A gentle-paced itinerary blending kid-friendly activities, elder-comfortable logistics, private vehicles and an immersive farmhouse homestay.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "Oct–Dec · Mar–Apr",
    groupSize: "Private tour — any family size",
    idealFor: "Multi-generational families with children and/or elderly travellers",
    overview:
      "A gentle-paced itinerary curated for multi-generational travel, blending kid-friendly activities, elder-comfortable logistics, private chauffeured vehicles and immersive homestay experiences for a wholesome family adventure in Bhutan.",
    highlights: [
      "Slower daily pace with shorter drive segments",
      "Hands-on kid-friendly activities: archery, art workshops, pony rides",
      "Authentic farmhouse homestay for cultural immersion",
      "Private chauffeur-driven vehicle throughout — no group coach",
      "Optional pony-assisted ascent for the Taktsang hike",
    ],
    includes: [
      "6 nights' accommodation (family rooms / interconnecting rooms available)",
      "Daily breakfast, lunch and dinner including farmhouse-hosted meal",
      "Private vehicle with child seats (on request)",
      "All entrance fees and homestay experience fee",
      "SDF and visa processing assistance",
      "Complimentary welcome gift and farewell keepsake for children",
    ],
    excludes: [...commonExcludes, "Pony rental fee for Taktsang hike (payable locally, optional)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Warm welcome at Paro Airport and an easy private drive to Thimphu. Evening hotel check-in and a relaxed family dinner featuring mild Bhutanese dishes suitable for children." },
      { day: 2, title: "Thimphu with the kids", desc: "A family-friendly day at Motithang Takin Preserve to meet Bhutan's national animal, followed by an archery demonstration and a hands-on painting session at the Voluntary Artists' Studio." },
      { day: 3, title: "Thimphu — Punakha", desc: "Drive to Punakha via Dochula Pass. Visit Punakha Dzong and enjoy a riverside walk, followed by a crossing of the longest suspension bridge in Bhutan." },
      { day: 4, title: "Punakha homestay experience", desc: "A full day at a local farmhouse — cook traditional meals, learn local customs, enjoy ara and butter tea, and join a friendly archery match with village hosts." },
      { day: 5, title: "Punakha — Paro", desc: "Scenic drive back to Paro. Afternoon at leisure — pony rides for younger children and a relaxed walk through Paro town's craft shops." },
      { day: 6, title: "Family hike to Taktsang", desc: "An easier-paced hike with pony option available to the cafeteria viewpoint. Farewell dinner with a private family cultural show." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport for departure, with keepsake gifts presented to the family by Golden Takin Holidays." },
    ],
  },
  {
    slug: "nature-and-eco-tours",
    title: "Nature & Eco Tours",
    category: "Nature & Eco",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Flora, Fauna & Conservation Trails",
    location: "Thimphu · Punakha · Phobjikha",
    price: 1490,
    image: bumthang,
    desc: "Conservation-led travel through Bhutan's forests, wetlands and glacial valleys with naturalist guides.",
    rating: 4.8,
    difficulty: "Moderate",
    bestTime: "Oct–Mar (crane season) · Apr–May (blooms)",
    groupSize: "2–12 pax, naturalist-guided",
    idealFor: "Nature lovers, eco-conscious travellers and small groups interested in Bhutan's conservation model",
    overview:
      "A conservation-focused circuit exploring Bhutan's forests, wetlands and protected valleys — from the Phobjikha black-necked crane habitat to rhododendron and magnolia trails — guided by trained naturalists.",
    highlights: [
      "Black-necked crane habitat visit in the Phobjikha wetlands",
      "Alpine meadow and rhododendron trails around Dochula Pass",
      "Community-based conservation and eco-lodge stays",
      "Naturalist-guided walks with species checklists",
      "Low-impact travel following Bhutan's carbon-negative model",
    ],
    includes: [
      "5 nights' accommodation in eco-lodges and guesthouses",
      "Daily breakfast, lunch and dinner",
      "Naturalist guide and private vehicle with driver",
      "All park entrance and conservation area fees",
      "SDF and visa processing assistance",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro Airport and private drive to Thimphu. Evening conservation briefing with your naturalist guide." },
      { day: 2, title: "Thimphu conservation circuit", desc: "Motithang Takin Preserve, the Royal Botanical Park and a forest walk covering Bhutan's endemic flora and protected species." },
      { day: 3, title: "Thimphu — Punakha via Dochula", desc: "Drive to Punakha over Dochula Pass with its 108 chortens and alpine meadow trail. Riverside birding in the Punakha valley." },
      { day: 4, title: "Phobjikha Valley — wetland conservation", desc: "Transfer to the glacial Phobjikha Valley. Visit the Black-Necked Crane Information Centre and walk the Gangtey Nature Trail among grazing yaks." },
      { day: 5, title: "Phobjikha — Paro", desc: "Morning wetland walk, then a scenic drive to Paro with panoramic Himalayan ridgeline stops along the way." },
      { day: 6, title: "Paro valley walk — departure", desc: "Kyichu Lhakhang and a final riverside valley walk before transfer to Paro International Airport." },
    ],
  },
  {
    slug: "geographical-expedition",
    title: "Geographical Expedition",
    category: "Geographical Expedition",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Himalayan Thrust & Landform Studies",
    location: "Paro · Punakha · Haa · Chele La",
    price: 1590,
    image: trekking,
    desc: "A fieldwork-oriented expedition through thrust zones, river confluences and glacial landforms, accompanied by a local geologist-guide.",
    rating: 4.7,
    difficulty: "Moderate",
    bestTime: "Apr–Jun · Sep–Nov",
    groupSize: "6–20 pax with geologist-guide",
    idealFor: "University geology/geography departments, research groups and expedition-style enthusiasts",
    overview:
      "An academic field itinerary built around the Himalayan thrust belt: exposed rock strata, river confluences, glacial valleys and high-pass landform observation, with stable weather windows for fieldwork and pass crossings.",
    highlights: [
      "Accompanied by a local geologist-guide throughout",
      "Exposed rock strata and thrust-zone field stops",
      "Punakha river confluence and fluvial landform study",
      "Chele La (3,988m) high-pass observation point",
      "Field notes, sampling stops and evening debrief sessions",
    ],
    includes: [
      "6 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Private expedition vehicle, driver and geologist-guide",
      "All field-site permits and entrance fees",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Specialist survey equipment and sample export permits"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Arrival briefing on Himalayan tectonics and the week's field plan. Overnight in Thimphu." },
      { day: 2, title: "Exposed rock strata", desc: "Field stops along road cuttings displaying folded and faulted strata of the Lesser Himalayan sequence." },
      { day: 3, title: "Dochula panoramic view", desc: "High-pass panorama of the eastern Himalayan range with orientation to glaciated peaks and watershed lines." },
      { day: 4, title: "Punakha river confluence", desc: "Study of the Pho Chhu and Mo Chhu confluence — terraces, braided channels and flood-plain deposition." },
      { day: 5, title: "Haa valley landscape", desc: "Transfer to the Haa valley for glacial trough and valley-floor morphology observation." },
      { day: 6, title: "Chele La pass", desc: "Ascent to Chele La for alpine landform, tree-line and weathering profile studies with valley-scale photography." },
      { day: 7, title: "Departure", desc: "Paro valley sunrise viewpoint, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "historical-tours",
    title: "Historical Tours",
    category: "Historical",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Dzongs, Fortresses & Royal Heritage",
    location: "Paro · Thimphu · Punakha",
    price: 1350,
    image: historical,
    desc: "A deep dive into Bhutan's architectural and dynastic history — from 17th-century fortress-monasteries to royal heritage sites — narrated by specialist historical guides.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Sep–Nov · Mar–May",
    groupSize: "2–16 pax with a specialist historical guide",
    idealFor: "History enthusiasts, heritage travellers and cultural researchers",
    overview:
      "A deep dive into Bhutan's architectural and dynastic history. The circuit moves from 17th-century fortress-monasteries to royal heritage sites and national museum collections, narrated throughout by a specialist historical guide.",
    highlights: [
      "Visits every major dzong along the western corridor",
      "In-depth narration on the unification of Bhutan and the dynastic timeline",
      "Museum-led sessions at the National Museum of Bhutan",
      "Drugyal Dzong ruins and their place in Bhutanese military history",
      "Culminates with the Taktsang Monastery pilgrimage",
    ],
    includes: [
      "5 nights' accommodation in heritage-style hotels",
      "Daily breakfast, lunch and dinner",
      "Specialist historical guide and private vehicle with driver",
      "Entrance fees to all dzongs, museums and heritage sites",
      "SDF and visa processing assistance",
      "Printed historical booklet and route notes",
    ],
    excludes: [...commonExcludes, "Photography permits inside restricted museum galleries", "Pony rental for the Taktsang hike (optional)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro International Airport and private drive to Thimphu. Evening orientation on Bhutan's dynastic timeline. Overnight in Thimphu." },
      { day: 2, title: "Thimphu historical sites", desc: "National Memorial Chorten, Tashichho Dzong, the National Library's ancient manuscripts and a museum-led session at the Folk Heritage Museum. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha via Dochula Pass", desc: "Drive over Dochula Pass to Punakha. In-depth tour of Punakha Dzong, seat of Bhutan's first coronation, and a crossing of the longest suspension bridge in Bhutan. Overnight in Punakha." },
      { day: 4, title: "Punakha — Wangdue Phodrang", desc: "Wangdue Phodrang Dzong and Chimi Lhakhang, with a session on regional governance and fortress architecture. Overnight in Punakha." },
      { day: 5, title: "Paro historical circuit", desc: "Return to Paro for Rinpung Dzong, the National Museum at Ta Dzong and the Drugyal Dzong ruins. Overnight in Paro." },
      { day: 6, title: "Taktsang Monastery — departure", desc: "Morning hike to Taktsang Monastery, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "wildlife-safari",
    title: "Wildlife Safari",
    category: "Wildlife",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Rare Species & Conservation Encounters",
    location: "Paro · Thimphu · Punakha · Phobjikha",
    price: 1690,
    image: wildlife,
    desc: "Focused itineraries targeting Bhutan's rare and endangered species, from the majestic takin to the black-necked crane, guided by wildlife specialists across protected conservation zones.",
    rating: 4.9,
    difficulty: "Moderate",
    bestTime: "Nov–Feb (black-necked crane) · year-round for takin",
    groupSize: "2–12 pax with a wildlife specialist guide",
    idealFor: "Wildlife photographers, conservationists and nature travellers",
    overview:
      "Focused itineraries targeting Bhutan's rare and endangered species — the golden takin, black-necked crane and Himalayan monal among them — guided by wildlife specialists across the Kingdom's protected conservation zones.",
    highlights: [
      "Targets flagship species: golden takin, black-necked crane and Himalayan monal",
      "Access to Phobjikha valley's protected crane wintering grounds",
      "Explores Bhutan's protected-area network and conservation policy",
      "Optional extension to Royal Manas National Park (quoted separately)",
      "Dedicated wildlife-photography review session",
    ],
    includes: [
      "6 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Wildlife specialist guide, spotting-scope access and private vehicle",
      "Entrance fees and protected-area permit assistance",
      "SDF and visa processing assistance",
      "Species checklist and field guide booklet",
    ],
    excludes: [...commonExcludes, "Royal Manas National Park extension (quoted separately on request)"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Arrival briefing on Bhutan's protected-area network, with a first look for Himalayan griffon over the Paro valley. Overnight in Thimphu." },
      { day: 2, title: "Thimphu wildlife circuit", desc: "Motithang Takin Preserve for Bhutan's national animal, followed by forest-edge birding and a conservation briefing. Overnight in Thimphu." },
      { day: 3, title: "Thimphu — Punakha", desc: "Drive to Punakha with wildlife stops en route; afternoon river-otter and riverine habitat watch along the Mo Chhu. Overnight in Punakha." },
      { day: 4, title: "Phobjikha valley — black-necked crane", desc: "Full day dedicated to Phobjikha, including the Black-Necked Crane Centre and cranes feeding in the valley marshland. Overnight in Phobjikha." },
      { day: 5, title: "Phobjikha — Paro", desc: "Return towards Paro with forest-trail stops for Himalayan monal and pheasant species in temperate forest. Overnight in Paro." },
      { day: 6, title: "Paro valley wildlife walk", desc: "Early morning wildlife walk near Kyichu Lhakhang and the Paro river corridor for valley birdlife at dawn. Overnight in Paro." },
      { day: 7, title: "Departure", desc: "Sunrise over the Paro valley, then transfer to Paro International Airport." },
    ],
  },
  {
    slug: "tropical-expedition",
    title: "Tropical Expedition",
    category: "Tropical Expedition",
    duration: "6 Days",
    nights: "5 Nights / 6 Days",
    tagline: "Subtropical Southern Bhutan",
    location: "Paro · Thimphu · Phuentsholing · Punakha",
    price: 1290,
    image: tropical,
    desc: "An offbeat itinerary into Bhutan's lesser-visited subtropical south — humid lowland forests, border towns and a striking contrast to the alpine north.",
    rating: 4.7,
    difficulty: "Easy",
    bestTime: "Nov–Feb (dry, comfortable lowland temperatures)",
    groupSize: "2–16 pax",
    idealFor: "Offbeat travellers wanting to see beyond the typical alpine circuit",
    overview:
      "An offbeat itinerary into Bhutan's lesser-visited subtropical south — humid lowland forests, border towns and tropical gardens — offering a striking contrast to the alpine north for travellers seeking a different side of the Kingdom.",
    highlights: [
      "One of the few itineraries to include Phuentsholing in southern Bhutan",
      "Visits the Crocodile Breeding Centre at Phuentsholing",
      "Traverses dramatic climatic transitions from alpine to subtropical zones",
      "Kharbandi Monastery's tropical gardens overlooking the southern plains",
      "Scenic descent and ascent drives through Bhutan's foothill forests",
    ],
    includes: [
      "5 nights' accommodation on twin-sharing basis",
      "Daily breakfast, lunch and dinner",
      "Licensed guide and private vehicle with driver",
      "Entrance fees to all sites listed in the itinerary",
      "SDF and visa processing assistance",
      "Border-town permit coordination",
    ],
    excludes: [...commonExcludes, "Any cross-border excursion into India"],
    itinerary: [
      { day: 1, title: "Arrival in Paro — transfer to Thimphu", desc: "Welcome at Paro International Airport and drive to Thimphu. Evening at leisure with a Bhutanese welcome dinner. Overnight in Thimphu." },
      { day: 2, title: "Thimphu — descent to Phuentsholing", desc: "Long, scenic descent through foothill forest as the climate shifts from temperate to subtropical. Overnight in Phuentsholing." },
      { day: 3, title: "Phuentsholing & southern foothills", desc: "Kharbandi Monastery gardens overlooking the southern plains, the Crocodile Breeding Centre and the Zangtho Pelri Lhakhang. Overnight in Phuentsholing." },
      { day: 4, title: "Phuentsholing — Punakha", desc: "Return ascent through central Bhutan, arriving in the Punakha valley by evening. Overnight in Punakha." },
      { day: 5, title: "Punakha — Paro", desc: "Punakha Dzong and Chimi Lhakhang in the morning, then a scenic drive back to Paro. Afternoon at leisure in Paro town. Overnight in Paro." },
      { day: 6, title: "Departure", desc: "Transfer to Paro International Airport with a farewell keepsake from Golden Takin Holidays." },
    ],
  },
  {
    slug: "buddhist-culture-tours",
    title: "Buddhist Culture & Historical Tour Package",
    category: "Buddhist Culture",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha – Wangdue – Gasa – Paro",
    location: "Paro · Thimphu · Punakha · Gasa",
    price: 1490,
    image: culture,
    desc: "A deep cultural submersion into Bhutan's living Buddhist heritage, tracing five major dzongs and sacred temples across the western valleys.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "March–May & September–November",
    groupSize: "2–16 pax",
    idealFor: "Cultural historians, pilgrims and heritage travellers",
    overview:
      "This tour is a deep cultural submersion into Bhutan's living Buddhist heritage, tracing five major dzongs and sacred temples across the western valleys — from Thimphu's seat of government to remote Gasa, one of the least-visited fortress-monasteries in the country. Trip grade: easy — temple and dzong visits with a licensed cultural guide.",
    highlights: [
      "Visits five major dzongs across three valleys",
      "Guided history session on Bhutan's 17th-century unification",
      "Licensed cultural/historical guide throughout",
      "Visits the Zorig Chusum Institute of Traditional Arts",
      "Includes remote Gasa Dzong, rarely visited by tourists",
      "Pilgrimage hike to Taktsang Monastery",
    ],
    includes: [
      "All accommodation on twin-sharing basis",
      "All meals throughout the tour",
      "Licensed cultural/historical guide and private vehicle with driver",
      "All monument, museum and temple entrance fees, airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening visit to the National Memorial Chorten and Changangkha Lhakhang. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu heritage sites", desc: "Visit Tashichho Dzong, Simtokha Dzong (one of Bhutan's oldest fortresses, built in 1629), and the Zorig Chusum Institute of Traditional Arts & Crafts. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass and its 108 memorial chortens, then visit Punakha Dzong, built in 1637 at the confluence of the Pho Chhu and Mo Chhu rivers, and Chimi Lhakhang. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha – Wangdue Phodrang", desc: "Visit Wangdue Phodrang Dzong, perched on a ridge above the Punakha valley, and the nearby weaving village of Rinchengang. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Gasa", desc: "Drive north along the Mo Chhu river valley to Gasa Dzong, a 17th-century fortress built to defend against Tibetan invasions and rarely visited by international tourists. Overnight at hotel, Gasa." },
      { day: 6, title: "Gasa – Paro", desc: "Return south via Punakha and Dochula Pass to Paro, stopping at Tamchog Lhakhang and Kyichu Lhakhang, one of Bhutan's oldest temples. Overnight at hotel, Paro." },
      { day: 7, title: "Taktsang Monastery hike & departure", desc: "Hike to Taktsang (Tiger's Nest) Monastery, Bhutan's most sacred pilgrimage site, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "hiking-and-trekking",
    title: "Hiking & Trekking",
    category: "Hiking & Trekking",
    duration: "7 Days",
    nights: "6 Nights / 7 Days",
    tagline: "Druk Path & Bumdra Trek",
    location: "Paro — Thimphu",
    price: 1750,
    image: trekking,
    desc: "An adventure itinerary combining the classic Druk Path Trek and Bumdra Trek routes, supported by full camping logistics, crew and safety protocols.",
    rating: 4.9,
    difficulty: "Challenging",
    bestTime: "Apr–Jun · Sep–Nov",
    groupSize: "2–12 pax with trek crew",
    idealFor: "Trekkers of varying experience levels seeking high-altitude trails",
    overview:
      "A high-altitude adventure itinerary combining the classic Druk Path Trek and Bumdra Trek routes, supported by comprehensive logistics, a full camping crew and clear safety protocols for trekkers of varying experience levels.",
    highlights: [
      "Classic Druk Path Trek across the ridge between Paro and Thimphu",
      "Camping beside the high-altitude Jimilangtsho Lake",
      "Jangchulakha high pastures at 3,780m with rhododendron forest approach",
      "Phajoding Monastery descent with panoramic Thimphu valley views",
      "Optional Bumdra day-hike above Taktsang",
    ],
    includes: [
      "Hotel nights in Paro and Thimphu plus full camping equipment on trek",
      "All meals on trek prepared by the camp kitchen crew",
      "Licensed trekking guide, cook, helpers and pack animals",
      "Trek permits, entrance fees and airport transfers",
      "SDF and visa processing assistance",
      "First-aid kit, oxygen and daily safety briefings",
    ],
    excludes: [...commonExcludes, "Personal trekking gear and sleeping bag", "Emergency evacuation costs"],
    itinerary: [
      { day: 1, title: "Arrival & gear check", desc: "Arrival in Paro, trek briefing and a full equipment check with the trek leader. Overnight in Paro." },
      { day: 2, title: "Jele Dzong — Jangchulakha", desc: "Trek through rhododendron forest and high pastures to the Jangchulakha camp at 3,780m. Overnight in camp." },
      { day: 3, title: "Jangchulakha — Jimilangtsho", desc: "Ridge-line trek passing several high-altitude lakes, camping beside Jimilangtsho Lake. Overnight in camp." },
      { day: 4, title: "Jimilangtsho — Phajoding", desc: "Descend past Phajoding Monastery with views over the Thimphu valley, then transfer to a Thimphu hotel. Overnight in Thimphu." },
      { day: 5, title: "Thimphu — Paro", desc: "Recovery morning in Thimphu, transfer to Paro and preparation for the Bumdra day-hike. Overnight in Paro." },
      { day: 6, title: "Bumdra day-hike above Taktsang", desc: "Optional Bumdra ascent with the descent route passing Taktsang Monastery. Overnight in Paro." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport with trek certificates presented by the crew." },
    ],
  },
  {
    slug: "birdwatching-tours",
    title: "Birdwatching Tours",
    category: "Birdwatching",
    duration: "8 Days",
    nights: "8 Days / 7 Nights",
    tagline: "Ornithology Expedition",
    location: "Paro · Thimphu · Punakha · Phobjikha",
    price: 1890,
    image: birdwatching,
    desc: "An expertly guided itinerary targeting Bhutan's avian diversity, from the elusive Ward's Trogon to the endangered Black-Necked Crane.",
    rating: 4.9,
    difficulty: "Moderate",
    bestTime: "Mar–May · Oct–Nov (peak migration)",
    groupSize: "Small groups with expert ornithologist guide",
    idealFor: "Ornithologists and avid birders",
    overview:
      "A highly focused, expertly guided itinerary designed for ornithology enthusiasts, targeting Bhutan's diverse avian species — from the elusive Ward's Trogon to the endangered Black-Necked Crane — with stops at key birding hotspots.",
    highlights: [
      "Expert ornithologist guide throughout",
      "High-altitude birding across Lawa La and Dochula",
      "Riverine species sightings in the Punakha valley",
      "Black-Necked Crane habitat visit in Phobjikha",
      "Species checklist provided and daily briefings",
    ],
    includes: [
      "All accommodation on twin-sharing basis including a retreat lodge stay in Punakha",
      "All meals (vegetarian options available throughout)",
      "Licensed ornithologist guide and private vehicle with driver",
      "All entrance fees and airport transfers",
      "SDF and visa processing assistance",
    ],
    excludes: [...commonExcludes, "Optics rental"],
    itinerary: [
      { day: 1, title: "Arrival — transfer to Thimphu", desc: "Evening birding checklist briefing. Overnight in hotel, Thimphu." },
      { day: 2, title: "Thimphu to Punakha via Lawa La", desc: "Target high-altitude species such as Satyr Tragopan along the pass. Overnight in hotel, Punakha." },
      { day: 3, title: "Punakha — Jigme Dorji National Park", desc: "Riverside birding for Ibisbill and riverine specialists. Overnight in hotel, Punakha." },
      { day: 4, title: "Punakha to Phobjikha", desc: "Drive through temperate forest for Ward's Trogon, then descend to the valley wetlands. Overnight in guesthouse, Phobjikha." },
      { day: 5, title: "Phobjikha full-day birding", desc: "Black-Necked Crane habitat and wetland circuit with the Gangtey ridge forest edge." },
      { day: 6, title: "Phobjikha to Paro", desc: "Return journey with final birding stops en route. Overnight in hotel, Paro." },
      { day: 7, title: "Paro valley & Taktsang trail birding", desc: "Early morning birding on the Tiger's Nest trail and along the Paro Chhu." },
      { day: 8, title: "Departure", desc: "Final checklist review and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "corporate-meetups-mice",
    title: "Corporate MICE Package",
    category: "Corporate & MICE",
    duration: "5 Days",
    nights: "5 Days / 4 Nights",
    tagline: "Thimphu – Paro",
    location: "Thimphu · Paro",
    price: 1390,
    image: corporate,
    desc: "Full-scale execution of off-site corporate programs, combining tech-enabled conference venues with Bhutan's cultural backdrop.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "Year-round (Oct–Apr recommended for indoor conference use)",
    groupSize: "Scalable to any company size",
    idealFor: "Corporate off-sites, leadership retreats, seminars and product launches",
    overview:
      "Corporate MICE Package delivers full-scale execution of off-site corporate programs in Thimphu and Paro, combining tech-enabled conference venues with Bhutan's cultural backdrop for team-building activities, gala dinners, and leadership retreats. Programs are customised per company size and objectives; the below is an indicative 5-day format.",
    highlights: [
      "Tech-enabled conference venues in Thimphu & Paro",
      "Dedicated corporate account manager",
      "Facilitated team-building activities",
      "Scalable to any company size or objective",
      "One customised gala dinner included",
      "Cultural excursions built around the work schedule",
    ],
    includes: [
      "Conference venue hire with standard AV/tech setup",
      "All accommodation on twin-sharing or single-occupancy basis (as required)",
      "All meals, working lunches, and one gala dinner",
      "Team-building activity facilitation and dedicated corporate account manager",
      "Private vehicle fleet and licensed guide(s), airport transfers",
    ],
    excludes: [
      "International and domestic airfare",
      "Sustainable Development Fee (SDF), collected directly by TCB",
      "Bhutan visa fee, travel insurance",
      "Custom branding/signage and specialised AV equipment beyond standard setup (quoted separately)",
    ],
    itinerary: [
      { day: 1, title: "Arrive Thimphu", desc: "Arrival and transfer to Thimphu. Evening welcome reception and program briefing with your dedicated corporate account manager. Overnight at hotel, Thimphu." },
      { day: 2, title: "Conference day 1", desc: "Full-day seminar/conference sessions at a tech-enabled venue in Thimphu, with coffee breaks and a working lunch arranged on-site. Overnight at hotel, Thimphu." },
      { day: 3, title: "Team-building & cultural immersion", desc: "Morning team-building activities (archery challenge, treasure hunt through Thimphu's landmarks), afternoon visit to Tashichho Dzong and Buddha Dordenma. Overnight at hotel, Thimphu." },
      { day: 4, title: "Thimphu – Paro, conference day 2 & gala dinner", desc: "Transfer to Paro for the closing session, followed by a customised gala dinner with traditional Bhutanese entertainment. Overnight at hotel, Paro." },
      { day: 5, title: "Departure", desc: "Optional morning excursion to Taktsang Monastery viewpoint for early arrivals, followed by transfer to Paro International Airport." },
    ],
  },
  {
    slug: "yoga-and-meditation-tours",
    title: "Yoga & Meditation Package",
    category: "Yoga & Wellness",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha",
    location: "Paro · Thimphu · Punakha",
    price: 1790,
    image: yoga,
    desc: "A slower, retreat-paced itinerary at monastery-affiliated retreat centres and riverside wellness lodges, with daily sessions led by local Buddhist masters.",
    rating: 4.9,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Small retreat groups",
    idealFor: "Wellness travellers, meditation practitioners and digital-detox seekers",
    overview:
      "A slower, retreat-paced itinerary hosted at monastery-affiliated retreat centres and riverside wellness lodges, with daily meditation and yoga sessions led by local Buddhist masters, interspersed with gentle sightseeing. Trip grade: easy — retreat-paced with daily sessions.",
    highlights: [
      "Daily sessions led by a local Buddhist master",
      "Slow, retreat-paced schedule",
      "Riverside retreat lodge stay in Punakha",
      "Mindful walk among Dochula Pass's 108 chortens",
      "Vegetarian meal options throughout",
      "Optional spa treatment in Paro",
    ],
    includes: [
      "All accommodation on twin-sharing basis, including retreat lodge stay in Punakha",
      "All meals (vegetarian options available throughout)",
      "Daily yoga/meditation sessions led by a local Buddhist master",
      "Licensed guide and private vehicle with driver, all entrance fees",
      "Airport transfers",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening grounding meditation session to settle in after travel. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu retreat day", desc: "Morning meditation session led by a local master, followed by an easy visit to Buddha Dordenma and the Takin Preserve. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass with a mindful walk among the 108 chortens, continuing to a riverside retreat lodge in Punakha. Overnight at retreat lodge, Punakha." },
      { day: 4, title: "Punakha yoga & meditation day", desc: "A full wellness day: morning yoga overlooking the Mo Chhu river, an afternoon visit to Chimi Lhakhang, and an evening guided meditation session. Overnight at retreat lodge, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Gentle drive back to Paro via Tamchog Lhakhang. Free afternoon for quiet reflection or a spa treatment. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang pilgrimage & departure", desc: "A mindful hike to Taktsang (Tiger's Nest) Monastery, one of Buddhism's holiest sites, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "school-college-cultural-exchange",
    title: "School & College Cultural Exchange Package",
    category: "School & College",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha",
    location: "Thimphu · Punakha · Paro",
    price: 1150,
    image: festival,
    desc: "A structured educational circuit focused on Gross National Happiness, sustainable architecture and Bhutanese history, designed with institutional partners.",
    rating: 4.8,
    difficulty: "Easy",
    bestTime: "October–April (school term-friendly)",
    groupSize: "Student groups, ages 14–22",
    idealFor: "CBSE/ICSE schools, colleges and student groups",
    overview:
      "A structured educational circuit for schools and colleges, focused on Gross National Happiness (GNH), sustainable architecture, and Bhutanese history — designed in coordination with institutional partners as part of Golden Takin Holidays' education desk. Trip grade: easy — structured educational circuit with group supervision.",
    highlights: [
      "Structured GNH and governance learning sessions",
      "Certificate of completion for participating students",
      "Dedicated education-desk coordinator",
      "Village homestay-style community interaction",
      "Group supervision rooms for accompanying staff",
      "Cultural quiz and closing ceremony",
    ],
    includes: [
      "Group accommodation on multi-share basis with dedicated supervision rooms for accompanying staff",
      "All meals throughout the tour",
      "Licensed educational guide(s) and private coach/vehicles scaled to group size",
      "All monument and temple entrance fees, structured learning sessions",
      "Airport transfers and a dedicated education-desk coordinator",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Group arrival and transfer to Thimphu. Evening orientation session on Bhutanese culture and etiquette. Overnight at hotel, Thimphu." },
      { day: 2, title: "GNH & governance study day", desc: "Visit to Tashichho Dzong, seat of the Bhutanese government, with an educational session on the Gross National Happiness development philosophy. Overnight at hotel, Thimphu." },
      { day: 3, title: "Traditional arts & sustainable architecture", desc: "Visit the Zorig Chusum Institute of Traditional Arts & Crafts, the Paper Factory, and a briefing on traditional rammed-earth and timber construction techniques still used across Bhutan. Overnight at hotel, Thimphu." },
      { day: 4, title: "Thimphu – Punakha, history day", desc: "Cross Dochula Pass and visit Punakha Dzong, with a guided historical session on the Zhabdrung's unification of Bhutan in the 17th century. Overnight at hotel, Punakha." },
      { day: 5, title: "Community & environment day", desc: "Village walk and interaction with a local farming family, plus an environmental briefing on Bhutan's constitutionally mandated forest cover and conservation policy. Overnight at hotel, Punakha." },
      { day: 6, title: "Punakha – Paro", desc: "Return to Paro via Tamchog Lhakhang. Evening student reflection session and cultural quiz. Overnight at hotel, Paro." },
      { day: 7, title: "Taktsang hike & departure", desc: "Group hike to Taktsang Monastery, followed by a closing ceremony and transfer to Paro International Airport." },
    ],
  },
  {
    slug: "honeymoon-trips",
    title: "Honeymoon Package",
    category: "Honeymoon",
    duration: "6 Days",
    nights: "6 Days / 5 Nights",
    tagline: "Paro – Thimphu – Punakha – Paro",
    location: "Paro · Thimphu · Punakha",
    price: 2190,
    image: tigersNest,
    desc: "A romantic-paced journey through Bhutan's most scenic valleys, with private candlelit dinners, couple's spa time and quiet moments built into each day.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Private — exclusively for the couple",
    idealFor: "Newlyweds and couples seeking a romantic getaway",
    overview:
      "Honeymoon Package is a romantic-paced journey through Bhutan's most scenic valleys, with private candlelit dinners, couple's spa time, and quiet moments built into each day — without the scale of a full destination wedding production. Trip grade: easy — leisure paced with private experiences.",
    highlights: [
      "One private candlelit dinner included",
      "Flexible pacing — nothing feels rushed",
      "Couple's spa session at a partner hotel",
      "Riverside hotel stay in Punakha",
      "Private vehicle and guide exclusively for you",
      "Optional private cultural performance",
    ],
    includes: [
      "Accommodation in couple-oriented rooms/suites where available",
      "All meals, including one private candlelit dinner",
      "Private vehicle with driver and licensed guide throughout",
      "All monument and temple entrance fees, airport transfers",
      "One couple's spa session (subject to hotel availability)",
    ],
    excludes: commonExcludes,
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Private welcome and transfer to Thimphu. Evening visit to the National Memorial Chorten at dusk, followed by a private welcome dinner. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu sightseeing", desc: "Visit Buddha Dordenma and Tashichho Dzong for the evening flag ceremony. Afternoon free for couple's spa treatments. Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Cross Dochula Pass together and visit Chimi Lhakhang, the Fertility Temple, considered especially auspicious for couples. Check into a riverside hotel overlooking the Mo Chhu. Overnight at hotel, Punakha." },
      { day: 4, title: "Punakha romantic day", desc: "Visit Punakha Dzong, then enjoy a private riverside picnic lunch. Evening candlelit dinner arranged on your hotel terrace. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Return to Paro via Tamchog Lhakhang. Afternoon at leisure, with an optional private cultural performance in the evening. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang couple's hike & departure", desc: "Hike together to Taktsang (Tiger's Nest) Monastery, followed by a private lunch with valley views, before transferring to Paro International Airport." },
    ],
  },
  {
    slug: "himalayan-wedding-ceremonies",
    title: "Destination Wedding Package",
    category: "Weddings",
    duration: "7 Days",
    nights: "7 Days / 6 Nights",
    tagline: "Paro – Thimphu – Punakha – Paro",
    location: "Paro · Thimphu · Punakha",
    price: 2890,
    image: wedding,
    desc: "Our full-production offering — venue selection, monk blessings, traditional attire, photography and every ceremonial detail coordinated end to end.",
    rating: 5.0,
    difficulty: "Easy",
    bestTime: "Mar–May · Sep–Nov",
    groupSize: "Couples and guest parties",
    idealFor: "Couples hosting a wedding or vow-renewal ceremony in Bhutan",
    overview:
      "Destination Wedding Package is our full-production offering: Golden Takin Holidays coordinates venue selection, monk blessings, traditional attire, photography, and every ceremonial detail, using premium hotel and resort partners such as Uma Paro, Amankora, and Six Senses Bhutan. Trip grade: easy — leisure paced with a full ceremony production day.",
    highlights: [
      "Dedicated wedding coordinator from Day 1",
      "Choice of premium resort partners",
      "Traditional Marchang blessing ceremony",
      "Archery demonstration and folk performance evening",
      "Professional photography & videography included",
      "Keepsake farewell gift on departure",
    ],
    includes: [
      "Accommodation on the selected circuit (premium/luxury options available)",
      "Dedicated wedding coordinator and full ceremony planning",
      "Traditional attire hire, monk blessing ceremony and Marchang ritual",
      "Professional photography and videography",
      "All meals, private vehicle with driver, and licensed guide",
      "Airport transfers",
    ],
    excludes: [
      "International and domestic airfare",
      "Sustainable Development Fee (SDF), collected directly by TCB",
      "Bhutan visa fee, travel insurance",
      "Guest list travel costs beyond the couple (quoted separately for group bookings)",
    ],
    itinerary: [
      { day: 1, title: "Arrive Paro – Thimphu", desc: "Arrival and transfer to Thimphu. Evening welcome dinner with your dedicated wedding coordinator to confirm ceremony arrangements. Overnight at hotel, Thimphu." },
      { day: 2, title: "Thimphu sightseeing & ceremony planning", desc: "Visit Buddha Dordenma and Tashichho Dzong, then meet with monks for a pre-wedding blessing consultation. Fitting for traditional Bhutanese wedding attire (gho and kira). Overnight at hotel, Thimphu." },
      { day: 3, title: "Thimphu – Punakha", desc: "Drive to Punakha via Dochula Pass. Visit Chimi Lhakhang, the Fertility Temple, before checking into a riverside venue overlooking the Mo Chhu. Overnight at hotel, Punakha." },
      { day: 4, title: "Wedding ceremony day", desc: "The ceremony opens with a traditional Marchang libation ritual and monk blessings, followed by the exchange of vows against a Punakha Dzong or riverside backdrop. Evening celebratory dinner with archery demonstrations and folk performances. Overnight at hotel, Punakha." },
      { day: 5, title: "Punakha – Paro", desc: "Leisurely drive back to Paro via Tamchog Lhakhang. Afternoon at leisure — spa treatments available. Overnight at hotel, Paro." },
      { day: 6, title: "Taktsang couple's hike", desc: "Hike together to Taktsang Monastery, followed by a private picnic lunch. Evening farewell dinner and photo album handover. Overnight at hotel, Paro." },
      { day: 7, title: "Departure", desc: "Transfer to Paro International Airport, with a keepsake gift from Golden Takin Holidays." },
    ],
  },
];

export const categories = [
  "All Tours",
  "Group Tours",
  "Family Tours",
  "Nature & Eco",
  "Geographical Expedition",
  "Historical",
  "Wildlife",
  "Tropical Expedition",
  "Buddhist Culture",
  "Hiking & Trekking",
  "Birdwatching",
  "Corporate & MICE",
  "Yoga & Wellness",
  "School & College",
  "Honeymoon",
  "Weddings",
];

export const destinations = [
  { name: "Paro", desc: "Sacred valley, Taktsang & international gateway", image: tigersNest, slug: "paro" },
  { name: "Thimphu", desc: "Capital of a kingdom in the clouds", image: thimphu, slug: "thimphu" },
  { name: "Punakha", desc: "Former winter capital, dzong & river confluence", image: punakha, slug: "punakha" },
  { name: "Phobjikha", desc: "Glacial valley & black-necked crane habitat", image: bumthang, slug: "phobjikha" },
];

export const experiences = [
  { title: "Cultural Exchange & GNH", desc: "Heritage circuits, dzong studies and hands-on craft workshops with master artisans.", image: festival },
  { title: "Wellness & Meditation", desc: "Monastery retreats, daily guided practice and traditional hot-stone baths.", image: yoga },
  { title: "Nature, Birding & Conservation", desc: "Wetland walks, crane habitats and naturalist-guided forest trails.", image: birdwatching },
  { title: "Celebrations & Corporate", desc: "Destination weddings, gala dinners and tech-enabled executive retreats.", image: corporate },
];
